// Auto-generated by agents_sync.mjs — Claude Code session/agent activity.
// Native (no server, no ~/.claude hooks). Cost = API-equivalent. Do not hand-edit.
window.DASHBOARD_AGENTS = {
  "generated": "2026-10-03T13:00:57.327Z",
  "source": "ccusage + ~/.claude/projects (native, no hooks)",
  "totals": {
    "sessions": 809,
    "cost": 21526.9,
    "tokens": 22154449448,
    "activeToday": 5,
    "active7d": 75,
    "projects": 32
  },
  "byProject": [
    {
      "project": "worktree",
      "sessions": 295,
      "cost": 6362.96,
      "tokens": 7112445852
    },
    {
      "project": "BIMpossible Workspace",
      "sessions": 125,
      "cost": 4531.37,
      "tokens": 4628807571
    },
    {
      "project": "BIMpossible",
      "sessions": 145,
      "cost": 4496.36,
      "tokens": 3833329785
    },
    {
      "project": "AI Dev",
      "sessions": 112,
      "cost": 2543.5,
      "tokens": 2035576992
    },
    {
      "project": "Add Ins",
      "sessions": 19,
      "cost": 935.09,
      "tokens": 1314664558
    },
    {
      "project": "AI Models Local",
      "sessions": 12,
      "cost": 725.42,
      "tokens": 719353787
    },
    {
      "project": "AI Dashboard",
      "sessions": 24,
      "cost": 577.98,
      "tokens": 654930045
    },
    {
      "project": "Families by BIMpossible",
      "sessions": 5,
      "cost": 313.46,
      "tokens": 300307482
    },
    {
      "project": "Dashboard",
      "sessions": 4,
      "cost": 250.71,
      "tokens": 439468566
    },
    {
      "project": "BIMpossible Site",
      "sessions": 6,
      "cost": 200.86,
      "tokens": 317010540
    },
    {
      "project": "Evidence Compiler",
      "sessions": 5,
      "cost": 148.3,
      "tokens": 143749255
    },
    {
      "project": "F--",
      "sessions": 4,
      "cost": 50.49,
      "tokens": 62092384
    },
    {
      "project": "(unknown)",
      "sessions": 7,
      "cost": 47.45,
      "tokens": 32071794
    },
    {
      "project": "Claude Profile",
      "sessions": 4,
      "cost": 46.77,
      "tokens": 75670418
    },
    {
      "project": "Claude Tools",
      "sessions": 6,
      "cost": 43.95,
      "tokens": 95583803
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 12 43737e",
      "sessions": 4,
      "cost": 38.58,
      "tokens": 43922078
    },
    {
      "project": "AI Server",
      "sessions": 3,
      "cost": 38.37,
      "tokens": 90178047
    },
    {
      "project": "Finance Dashboard",
      "sessions": 1,
      "cost": 28.12,
      "tokens": 55931041
    },
    {
      "project": "Revit Ops",
      "sessions": 6,
      "cost": 26.7,
      "tokens": 50310152
    },
    {
      "project": "YourBIMpossible",
      "sessions": 1,
      "cost": 19.51,
      "tokens": 22212496
    },
    {
      "project": "Claude Tools graphify",
      "sessions": 4,
      "cost": 19.49,
      "tokens": 38094175
    },
    {
      "project": "Preseason Pick em",
      "sessions": 3,
      "cost": 17.3,
      "tokens": 18097209
    },
    {
      "project": "Local Intel",
      "sessions": 1,
      "cost": 11.98,
      "tokens": 20322254
    },
    {
      "project": "PC Monitor",
      "sessions": 1,
      "cost": 11.1,
      "tokens": 14935550
    },
    {
      "project": "BIMpossible AddIns",
      "sessions": 3,
      "cost": 8.7,
      "tokens": 6195057
    },
    {
      "project": "zCSuite Artifacts",
      "sessions": 1,
      "cost": 8.63,
      "tokens": 2675564
    },
    {
      "project": "D--",
      "sessions": 2,
      "cost": 6.53,
      "tokens": 10412308
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 21 aa524b",
      "sessions": 1,
      "cost": 6.28,
      "tokens": 5276442
    },
    {
      "project": "Users Zeria Downloads",
      "sessions": 1,
      "cost": 3.17,
      "tokens": 2101528
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 07 6a6ce1",
      "sessions": 1,
      "cost": 3.06,
      "tokens": 1893084
    },
    {
      "project": "Users Zeria AppData Local Programs OpenWhispr",
      "sessions": 1,
      "cost": 2.3,
      "tokens": 5711812
    },
    {
      "project": "Brother",
      "sessions": 2,
      "cost": 2.19,
      "tokens": 1117819
    }
  ],
  "recent": [
    {
      "id": "3450b729",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "haiku-4-5"
      ],
      "cost": 78.44,
      "tokens": 135146518,
      "lastActivity": "2026-10-01T21:14:53.453Z"
    },
    {
      "id": "d272f22e",
      "project": "worktree",
      "models": [
        "fable-5-1",
        "sonnet-5"
      ],
      "cost": 13.58,
      "tokens": 20565074,
      "lastActivity": "2026-10-01T20:50:20.550Z"
    },
    {
      "id": "98804545",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 108.22,
      "tokens": 144773647,
      "lastActivity": "2026-10-01T19:20:10.051Z"
    },
    {
      "id": "4b945f64",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 19.54,
      "tokens": 44027093,
      "lastActivity": "2026-10-01T19:11:52.098Z"
    },
    {
      "id": "46a0165d",
      "project": "F--",
      "models": [
        "opus-5-5"
      ],
      "cost": 3.05,
      "tokens": 4658246,
      "lastActivity": "2026-09-30T21:16:48.847Z"
    },
    {
      "id": "5b9b11c4",
      "project": "BIMpossible",
      "models": [
        "opus-5-5"
      ],
      "cost": 4.87,
      "tokens": 7037659,
      "lastActivity": "2026-09-30T21:05:28.890Z"
    },
    {
      "id": "e724d746",
      "project": "BIMpossible Workspace",
      "models": [
        "opus-5-5"
      ],
      "cost": 7.85,
      "tokens": 11214884,
      "lastActivity": "2026-09-30T21:05:03.262Z"
    },
    {
      "id": "71b4e731",
      "project": "Revit Ops",
      "models": [
        "opus-5-5"
      ],
      "cost": 2.03,
      "tokens": 4155883,
      "lastActivity": "2026-09-30T20:41:19.559Z"
    },
    {
      "id": "f7e32131",
      "project": "Revit Ops",
      "models": [
        "opus-5-5"
      ],
      "cost": 2.99,
      "tokens": 7637993,
      "lastActivity": "2026-09-30T19:54:43.276Z"
    },
    {
      "id": "328dad2c",
      "project": "BIMpossible",
      "models": [
        "opus-5-5"
      ],
      "cost": 7.3,
      "tokens": 9949682,
      "lastActivity": "2026-09-30T19:53:24.937Z"
    },
    {
      "id": "29b3cc74",
      "project": "BIMpossible",
      "models": [
        "opus-5-5"
      ],
      "cost": 11.07,
      "tokens": 31860484,
      "lastActivity": "2026-09-30T18:34:02.964Z"
    },
    {
      "id": "44552b17",
      "project": "BIMpossible",
      "models": [
        "opus-5-5"
      ],
      "cost": 0.51,
      "tokens": 408364,
      "lastActivity": "2026-09-30T17:34:34.281Z"
    },
    {
      "id": "9fde6c4a",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 6.93,
      "tokens": 12894135,
      "lastActivity": "2026-09-30T17:34:33.742Z"
    },
    {
      "id": "9a678a1d",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 0.94,
      "tokens": 983983,
      "lastActivity": "2026-09-30T17:18:58.610Z"
    },
    {
      "id": "5d962122",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 7.69,
      "tokens": 10262755,
      "lastActivity": "2026-09-30T17:07:21.018Z"
    },
    {
      "id": "a6bb284d",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 0.13,
      "tokens": 501079,
      "lastActivity": "2026-09-30T17:02:59.992Z"
    },
    {
      "id": "07542a44",
      "project": "BIMpossible",
      "models": [
        "opus-5-5"
      ],
      "cost": 1.89,
      "tokens": 3787466,
      "lastActivity": "2026-09-30T14:46:51.571Z"
    },
    {
      "id": "79abfdea",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 5.02,
      "tokens": 8007587,
      "lastActivity": "2026-09-30T05:17:07.966Z"
    },
    {
      "id": "49f3dc2d",
      "project": "BIMpossible",
      "models": [
        "opus-5-5"
      ],
      "cost": 39.2,
      "tokens": 84107904,
      "lastActivity": "2026-09-30T05:12:37.542Z"
    },
    {
      "id": "802f2c7a",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 3.54,
      "tokens": 6790063,
      "lastActivity": "2026-09-30T05:03:48.672Z"
    },
    {
      "id": "5910cc2e",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 1.51,
      "tokens": 3481115,
      "lastActivity": "2026-09-30T04:23:18.963Z"
    },
    {
      "id": "48cf1adb",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 56.11,
      "tokens": 80384536,
      "lastActivity": "2026-09-30T03:14:24.442Z"
    },
    {
      "id": "045fd772",
      "project": "Claude Tools graphify",
      "models": [
        "opus-5-5"
      ],
      "cost": 0.96,
      "tokens": 1840459,
      "lastActivity": "2026-09-30T02:59:38.408Z"
    },
    {
      "id": "c516dc0e",
      "project": "BIMpossible",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 176.23,
      "tokens": 160119326,
      "lastActivity": "2026-09-30T02:48:07.668Z"
    },
    {
      "id": "fb4515c4",
      "project": "Claude Tools graphify",
      "models": [
        "opus-5-5",
        "haiku-4-5"
      ],
      "cost": 16.2,
      "tokens": 31922079,
      "lastActivity": "2026-09-30T02:10:05.218Z"
    },
    {
      "id": "d8548371",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 82.63,
      "tokens": 66879586,
      "lastActivity": "2026-09-29T21:41:05.530Z"
    },
    {
      "id": "73a08a2d",
      "project": "Revit Ops",
      "models": [
        "opus-5-5"
      ],
      "cost": 7.03,
      "tokens": 13359734,
      "lastActivity": "2026-09-29T20:18:14.420Z"
    },
    {
      "id": "e2a1da45",
      "project": "worktree",
      "models": [
        "sonnet-5"
      ],
      "cost": 0.79,
      "tokens": 1081042,
      "lastActivity": "2026-09-29T18:02:26.788Z"
    },
    {
      "id": "c44242b8",
      "project": "BIMpossible",
      "models": [
        "sonnet-5"
      ],
      "cost": 0.5,
      "tokens": 746516,
      "lastActivity": "2026-09-29T18:00:31.109Z"
    },
    {
      "id": "c787622a",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 6.97,
      "tokens": 16418294,
      "lastActivity": "2026-09-26T22:22:40.459Z"
    }
  ],
  "timeline": [
    {
      "date": "2026-09-05",
      "cost": 58.61,
      "sessions": 2
    },
    {
      "date": "2026-09-06",
      "cost": 879.96,
      "sessions": 13
    },
    {
      "date": "2026-09-07",
      "cost": 408.37,
      "sessions": 30
    },
    {
      "date": "2026-09-10",
      "cost": 226.89,
      "sessions": 0
    },
    {
      "date": "2026-09-11",
      "cost": 320.25,
      "sessions": 14
    },
    {
      "date": "2026-09-12",
      "cost": 321.08,
      "sessions": 25
    },
    {
      "date": "2026-09-13",
      "cost": 329.75,
      "sessions": 28
    },
    {
      "date": "2026-09-14",
      "cost": 56.62,
      "sessions": 13
    },
    {
      "date": "2026-09-16",
      "cost": 548.38,
      "sessions": 5
    },
    {
      "date": "2026-09-19",
      "cost": 0.27,
      "sessions": 0
    },
    {
      "date": "2026-09-20",
      "cost": 63.89,
      "sessions": 1
    },
    {
      "date": "2026-09-21",
      "cost": 395.2,
      "sessions": 0
    },
    {
      "date": "2026-09-22",
      "cost": 247.01,
      "sessions": 15
    },
    {
      "date": "2026-09-23",
      "cost": 475.68,
      "sessions": 13
    },
    {
      "date": "2026-09-24",
      "cost": 606.09,
      "sessions": 25
    },
    {
      "date": "2026-09-25",
      "cost": 347.56,
      "sessions": 17
    },
    {
      "date": "2026-09-26",
      "cost": 412.12,
      "sessions": 27
    },
    {
      "date": "2026-09-28",
      "cost": 18.45,
      "sessions": 0
    },
    {
      "date": "2026-09-29",
      "cost": 274.66,
      "sessions": 4
    },
    {
      "date": "2026-09-30",
      "cost": 53.04,
      "sessions": 21
    },
    {
      "date": "2026-10-01",
      "cost": 82.57,
      "sessions": 4
    }
  ],
  "health": {
    "cacheHitRate": 96,
    "errorRate": 4.8,
    "avgCostPerSession": 26.61,
    "avgTokensPerSession": 27384981,
    "toolCalls": 18624,
    "errors": 902,
    "scannedSessions": 75,
    "bounded": false,
    "modelMix": [
      {
        "model": "opus-4-8",
        "cost": 6204.63,
        "pct": 29
      },
      {
        "model": "fable-5",
        "cost": 5579.67,
        "pct": 26
      },
      {
        "model": "opus-5",
        "cost": 3474.15,
        "pct": 16
      },
      {
        "model": "sonnet-5",
        "cost": 2476.84,
        "pct": 12
      },
      {
        "model": "fable-5-1",
        "cost": 2243.8,
        "pct": 10
      },
      {
        "model": "opus-5-5",
        "cost": 1495.55,
        "pct": 7
      },
      {
        "model": "sonnet-4-6",
        "cost": 49.67,
        "pct": 0
      },
      {
        "model": "haiku-4-5",
        "cost": 2.02,
        "pct": 0
      },
      {
        "model": "qwen3-coder-32k",
        "cost": 0.54,
        "pct": 0
      },
      {
        "model": "qwen3-coder:30b-a3b-q4_K_M",
        "cost": 0.02,
        "pct": 0
      },
      {
        "model": "qwen2.5-coder:14b",
        "cost": 0,
        "pct": 0
      }
    ]
  },
  "tools": [
    {
      "name": "Bash",
      "count": 11712,
      "pct": 63
    },
    {
      "name": "PowerShell",
      "count": 1189,
      "pct": 6
    },
    {
      "name": "Edit",
      "count": 1053,
      "pct": 6
    },
    {
      "name": "Write",
      "count": 856,
      "pct": 5
    },
    {
      "name": "Read",
      "count": 729,
      "pct": 4
    },
    {
      "name": "Agent",
      "count": 397,
      "pct": 2
    },
    {
      "name": "mcp__computer-use__computer_batch",
      "count": 373,
      "pct": 2
    },
    {
      "name": "mcp__mcp-server-for-revit__send_code_to_revit",
      "count": 353,
      "pct": 2
    },
    {
      "name": "SendUserFile",
      "count": 243,
      "pct": 1
    },
    {
      "name": "Grep",
      "count": 240,
      "pct": 1
    },
    {
      "name": "ToolSearch",
      "count": 239,
      "pct": 1
    },
    {
      "name": "mcp__claude-in-chrome__browser_batch",
      "count": 150,
      "pct": 1
    },
    {
      "name": "mcp__computer-use__zoom",
      "count": 131,
      "pct": 1
    },
    {
      "name": "mcp__claude-in-chrome__javascript_tool",
      "count": 119,
      "pct": 1
    },
    {
      "name": "SendMessage",
      "count": 96,
      "pct": 1
    },
    {
      "name": "mcp__computer-use__left_click",
      "count": 90,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__screenshot",
      "count": 85,
      "pct": 0
    },
    {
      "name": "Monitor",
      "count": 46,
      "pct": 0
    },
    {
      "name": "ListAgents",
      "count": 45,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__wait",
      "count": 45,
      "pct": 0
    },
    {
      "name": "TaskStop",
      "count": 40,
      "pct": 0
    },
    {
      "name": "Glob",
      "count": 34,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__search_session_transcripts",
      "count": 26,
      "pct": 0
    },
    {
      "name": "ReadNotifications",
      "count": 26,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__send_message",
      "count": 21,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__read_network_requests",
      "count": 20,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__list_sessions",
      "count": 19,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__computer",
      "count": 19,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__get_session",
      "count": 18,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__request_access",
      "count": 16,
      "pct": 0
    },
    {
      "name": "ReportFindings",
      "count": 15,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__navigate",
      "count": 15,
      "pct": 0
    },
    {
      "name": "WebFetch",
      "count": 13,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__find",
      "count": 13,
      "pct": 0
    },
    {
      "name": "Skill",
      "count": 12,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__mark_chapter",
      "count": 12,
      "pct": 0
    },
    {
      "name": "AskUserQuestion",
      "count": 8,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__open_application",
      "count": 8,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__double_click",
      "count": 8,
      "pct": 0
    },
    {
      "name": "mcp__ccd_pr__get_status",
      "count": 7,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__tabs_context_mcp",
      "count": 7,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__spawn_task",
      "count": 6,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__list_scheduled_tasks",
      "count": 5,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__scroll",
      "count": 5,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__type",
      "count": 5,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__get_draft",
      "count": 4,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__key",
      "count": 4,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__get_page_text",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__tabs_close_mcp",
      "count": 3,
      "pct": 0
    },
    {
      "name": "ScheduleWakeup",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__dismiss_task",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__create_scheduled_task",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__ccd_directory__change_directory",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__ccd_pr__set_auto_merge",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__create_draft",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__list_drafts",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__search_threads",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__update_scheduled_task",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__list_task_runs",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__write_clipboard",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__read_page",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__browser_batch",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__plugin_context7_context7__query-docs",
      "count": 1,
      "pct": 0
    },
    {
      "name": "WebSearch",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__list_events",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__stop_session",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__archive_session",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_directory__request_directory",
      "count": 1,
      "pct": 0
    },
    {
      "name": "EnterWorktree",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__update_draft",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__run_scheduled_task",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__autodesk-revit-2027__get_running_revit_instances",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__mouse_move",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__read_console_messages",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_pr__bind_pr",
      "count": 1,
      "pct": 0
    }
  ],
  "subagents": {
    "total": 403,
    "byProject": [
      {
        "project": "worktree",
        "count": 334
      },
      {
        "project": "BIMpossible",
        "count": 46
      },
      {
        "project": "AI Dashboard",
        "count": 14
      },
      {
        "project": "F--",
        "count": 6
      },
      {
        "project": "Claude Tools graphify",
        "count": 2
      },
      {
        "project": "BIMpossible Workspace",
        "count": 1
      }
    ],
    "scannedSessions": 75,
    "bounded": false
  },
  "workflow": {
    "subagentTypes": [
      {
        "type": "general-purpose",
        "count": 205
      },
      {
        "type": "security-engineer",
        "count": 65
      },
      {
        "type": "qa-engineer",
        "count": 30
      },
      {
        "type": "Explore",
        "count": 29
      },
      {
        "type": "typescript-api-reviewer",
        "count": 28
      },
      {
        "type": "backend-endpoint-reviewer",
        "count": 22
      },
      {
        "type": "migration-reviewer",
        "count": 18
      },
      {
        "type": "pr-review-toolkit:code-reviewer",
        "count": 2
      },
      {
        "type": "bim-manager",
        "count": 2
      },
      {
        "type": "claude-code-guide",
        "count": 1
      },
      {
        "type": "tech-lead",
        "count": 1
      }
    ],
    "avgSubagentsPerSession": 5.37,
    "successRate": 95.2,
    "topSubagentType": "general-purpose",
    "mostCommonTool": "Bash"
  },
  "analytics": {
    "totalSessions": 809,
    "totalTokens": 22154449448,
    "totalCost": 21526.9,
    "events": 169560,
    "byWeekday": [
      {
        "day": "Sun",
        "cost": 3835.93
      },
      {
        "day": "Mon",
        "cost": 2847.85
      },
      {
        "day": "Tue",
        "cost": 3490.7
      },
      {
        "day": "Wed",
        "cost": 3024.22
      },
      {
        "day": "Thu",
        "cost": 2389.72
      },
      {
        "day": "Fri",
        "cost": 2825.81
      },
      {
        "day": "Sat",
        "cost": 3112.68
      }
    ]
  },
  "config": {
    "skills": 16,
    "subagents": 8,
    "commands": 0,
    "outputStyles": 0,
    "plugins": 7,
    "mcpServers": 0,
    "hooks": 11,
    "keybindings": 0,
    "memory": 537
  },
  "recentEvents": [
    {
      "ts": "2026-10-01T21:14:34.564Z",
      "tool": "SendUserFile",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:14:29.958Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:14:23.518Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:14:17.846Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:14:09.787Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:14:02.886Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:13:55.322Z",
      "tool": "mcp__ccd_pr__get_status",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:13:52.848Z",
      "tool": "ToolSearch",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:13:45.771Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:13:35.543Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:13:29.349Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:12:12.534Z",
      "tool": "ToolSearch",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:12:09.868Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:12:06.590Z",
      "tool": "Write",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:12:01.016Z",
      "tool": "Write",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:11:41.985Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:11:36.973Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:11:25.676Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:11:21.371Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:11:12.926Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:11:09.782Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:11:05.883Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:11:00.198Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:10:45.973Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:10:37.182Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:10:33.824Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:10:28.184Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:10:26.781Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:10:20.863Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:10:05.322Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:59.626Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:53.983Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:51.576Z",
      "tool": "Edit",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:46.398Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:43.027Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:35.747Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:34.694Z",
      "tool": "Edit",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:33.346Z",
      "tool": "Edit",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:26.102Z",
      "tool": "Edit",
      "project": "worktree",
      "session": "3450b729"
    },
    {
      "ts": "2026-10-01T21:09:19.353Z",
      "tool": "Edit",
      "project": "worktree",
      "session": "3450b729"
    }
  ]
};
