// Auto-generated by agents_sync.mjs — Claude Code session/agent activity.
// Native (no server, no ~/.claude hooks). Cost = API-equivalent. Do not hand-edit.
window.DASHBOARD_AGENTS = {
  "generated": "2026-10-08T13:00:26.321Z",
  "source": "ccusage + ~/.claude/projects (native, no hooks)",
  "totals": {
    "sessions": 985,
    "cost": 23219.07,
    "tokens": 24709033023,
    "activeToday": 23,
    "active7d": 187,
    "projects": 139
  },
  "byProject": [
    {
      "project": "worktree",
      "sessions": 342,
      "cost": 7498.69,
      "tokens": 8886877748
    },
    {
      "project": "BIMpossible",
      "sessions": 148,
      "cost": 4788.37,
      "tokens": 4161231964
    },
    {
      "project": "BIMpossible Workspace",
      "sessions": 127,
      "cost": 4551.59,
      "tokens": 4667692707
    },
    {
      "project": "AI Dev",
      "sessions": 112,
      "cost": 2543.5,
      "tokens": 2035576992
    },
    {
      "project": "Add Ins",
      "sessions": 19,
      "cost": 935.09,
      "tokens": 1314664558
    },
    {
      "project": "AI Models Local",
      "sessions": 12,
      "cost": 725.42,
      "tokens": 719353787
    },
    {
      "project": "AI Dashboard",
      "sessions": 27,
      "cost": 615.8,
      "tokens": 819197632
    },
    {
      "project": "Families by BIMpossible",
      "sessions": 5,
      "cost": 313.46,
      "tokens": 300307482
    },
    {
      "project": "Dashboard",
      "sessions": 4,
      "cost": 250.71,
      "tokens": 439468566
    },
    {
      "project": "BIMpossible Site",
      "sessions": 6,
      "cost": 200.86,
      "tokens": 317010540
    },
    {
      "project": "Evidence Compiler",
      "sessions": 5,
      "cost": 148.3,
      "tokens": 143749255
    },
    {
      "project": "F--",
      "sessions": 6,
      "cost": 63.35,
      "tokens": 96813869
    },
    {
      "project": "Local Intel",
      "sessions": 2,
      "cost": 55.67,
      "tokens": 60745288
    },
    {
      "project": "(unknown)",
      "sessions": 7,
      "cost": 47.45,
      "tokens": 32071794
    },
    {
      "project": "Claude Profile",
      "sessions": 4,
      "cost": 46.77,
      "tokens": 75670418
    },
    {
      "project": "Claude Tools",
      "sessions": 6,
      "cost": 43.95,
      "tokens": 95583803
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 12 43737e",
      "sessions": 4,
      "cost": 38.58,
      "tokens": 43922078
    },
    {
      "project": "AI Server",
      "sessions": 3,
      "cost": 38.37,
      "tokens": 90178047
    },
    {
      "project": "Team Claude",
      "sessions": 1,
      "cost": 33.88,
      "tokens": 43470502
    },
    {
      "project": "Revit Ops",
      "sessions": 8,
      "cost": 31.59,
      "tokens": 60745645
    },
    {
      "project": "Finance Dashboard",
      "sessions": 1,
      "cost": 28.12,
      "tokens": 55931041
    },
    {
      "project": "Claude Tools graphify",
      "sessions": 5,
      "cost": 25.31,
      "tokens": 48992135
    },
    {
      "project": "My Drive Coord Desktop AI ClickUp and Claude",
      "sessions": 7,
      "cost": 21.13,
      "tokens": 41914910
    },
    {
      "project": "YourBIMpossible",
      "sessions": 1,
      "cost": 19.51,
      "tokens": 22212496
    },
    {
      "project": "Personal Project Platform",
      "sessions": 1,
      "cost": 17.48,
      "tokens": 35074022
    },
    {
      "project": "Preseason Pick em",
      "sessions": 3,
      "cost": 17.3,
      "tokens": 18097209
    },
    {
      "project": "PC Monitor",
      "sessions": 1,
      "cost": 11.1,
      "tokens": 14935550
    },
    {
      "project": "BIMpossible AddIns",
      "sessions": 3,
      "cost": 8.7,
      "tokens": 6195057
    },
    {
      "project": "zCSuite Artifacts",
      "sessions": 1,
      "cost": 8.63,
      "tokens": 2675564
    },
    {
      "project": "ClickUp AI",
      "sessions": 3,
      "cost": 8.29,
      "tokens": 24949763
    },
    {
      "project": "Users Zeria AppData Local Temp ai label cjty584b",
      "sessions": 1,
      "cost": 6.85,
      "tokens": 342007
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 89mj33l0",
      "sessions": 1,
      "cost": 6.85,
      "tokens": 341900
    },
    {
      "project": "D--",
      "sessions": 2,
      "cost": 6.53,
      "tokens": 10412308
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 21 aa524b",
      "sessions": 1,
      "cost": 6.28,
      "tokens": 5276442
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 63siy49p",
      "sessions": 1,
      "cost": 3.78,
      "tokens": 188219
    },
    {
      "project": "Users Zeria AppData Local Temp ai label pue6ux5n",
      "sessions": 1,
      "cost": 3.77,
      "tokens": 188147
    },
    {
      "project": "Users Zeria Downloads",
      "sessions": 1,
      "cost": 3.17,
      "tokens": 2101528
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 07 6a6ce1",
      "sessions": 1,
      "cost": 3.06,
      "tokens": 1893084
    },
    {
      "project": "Users Zeria AppData Local Temp ai label ra61h4lc",
      "sessions": 1,
      "cost": 2.72,
      "tokens": 339160
    },
    {
      "project": "Users Zeria AppData Local Programs OpenWhispr",
      "sessions": 1,
      "cost": 2.3,
      "tokens": 5711812
    },
    {
      "project": "Users Zeria AppData Local Temp ai label tzo5o53x",
      "sessions": 1,
      "cost": 2.25,
      "tokens": 281490
    },
    {
      "project": "Brother",
      "sessions": 2,
      "cost": 2.19,
      "tokens": 1117819
    },
    {
      "project": "Users Zeria AppData Local Temp ai label ho6fb5ji",
      "sessions": 1,
      "cost": 2.16,
      "tokens": 269290
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 2z7qkm2t",
      "sessions": 1,
      "cost": 2.16,
      "tokens": 269427
    },
    {
      "project": "Users Zeria AppData Local Temp ai label mo0zdmlq",
      "sessions": 1,
      "cost": 2,
      "tokens": 249725
    },
    {
      "project": "Users Zeria AppData Local Temp ai label rth67j f",
      "sessions": 1,
      "cost": 1.98,
      "tokens": 247196
    },
    {
      "project": "Users Zeria AppData Local Temp ai label g1qgplyg",
      "sessions": 1,
      "cost": 1.97,
      "tokens": 246003
    },
    {
      "project": "Users Zeria AppData Local Temp ai label a2rt0 l",
      "sessions": 1,
      "cost": 1.86,
      "tokens": 231779
    },
    {
      "project": "Users Zeria AppData Local Temp ai label upjvbew4",
      "sessions": 1,
      "cost": 1.85,
      "tokens": 231940
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 2rsi vbk",
      "sessions": 1,
      "cost": 1.83,
      "tokens": 229377
    },
    {
      "project": "Users Zeria AppData Local Temp ai label isutmwyc",
      "sessions": 1,
      "cost": 1.76,
      "tokens": 219656
    },
    {
      "project": "Users Zeria AppData Local Temp ai label kalq6mgh",
      "sessions": 1,
      "cost": 1.75,
      "tokens": 219560
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 1wyjbh9t",
      "sessions": 1,
      "cost": 1.49,
      "tokens": 185464
    },
    {
      "project": "Users Zeria AppData Local Temp ai label g0thhkuh",
      "sessions": 1,
      "cost": 1.36,
      "tokens": 339789
    },
    {
      "project": "Users Zeria AppData Local Temp ai label y4b a1s2",
      "sessions": 1,
      "cost": 1.35,
      "tokens": 338873
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 01fgg5i5",
      "sessions": 1,
      "cost": 0.77,
      "tokens": 372959
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 6l33664x",
      "sessions": 1,
      "cost": 0.74,
      "tokens": 185497
    },
    {
      "project": "Users Zeria AppData Local Temp ai label trqw5pql",
      "sessions": 1,
      "cost": 0.33,
      "tokens": 41919
    },
    {
      "project": "Users Zeria AppData Local Temp ai label z6 3rw0a",
      "sessions": 1,
      "cost": 0.32,
      "tokens": 15599
    },
    {
      "project": "Users Zeria AppData Local Temp ai label aaueao4",
      "sessions": 1,
      "cost": 0.32,
      "tokens": 15681
    },
    {
      "project": "Users Zeria AppData Local Temp ai label p92rrsyu",
      "sessions": 1,
      "cost": 0.31,
      "tokens": 152035
    },
    {
      "project": "Users Zeria AppData Local Temp ai label wqo5btva",
      "sessions": 1,
      "cost": 0.28,
      "tokens": 35046
    },
    {
      "project": "Users Zeria AppData Local Temp ai label kblc8ko",
      "sessions": 1,
      "cost": 0.28,
      "tokens": 13609
    },
    {
      "project": "Users Zeria AppData Local Temp ai label a7k 5oew",
      "sessions": 1,
      "cost": 0.27,
      "tokens": 13508
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 2moz0lnw",
      "sessions": 1,
      "cost": 0.25,
      "tokens": 31403
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 10 07 9ef885",
      "sessions": 1,
      "cost": 0.22,
      "tokens": 344603
    },
    {
      "project": "Users Zeria AppData Local Temp ai label ghxmi68",
      "sessions": 1,
      "cost": 0.19,
      "tokens": 23562
    },
    {
      "project": "Users Zeria AppData Local Temp ai label mi5ordhv",
      "sessions": 1,
      "cost": 0.16,
      "tokens": 20786
    },
    {
      "project": "Users Zeria AppData Local Temp ai label ertp6exx",
      "sessions": 1,
      "cost": 0.16,
      "tokens": 18870
    },
    {
      "project": "Users Zeria AppData Local Temp ai label rijx4irq",
      "sessions": 1,
      "cost": 0.15,
      "tokens": 72062
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 7tml417k",
      "sessions": 1,
      "cost": 0.14,
      "tokens": 35164
    },
    {
      "project": "Users Zeria AppData Local Temp ai label jt6qw5ii",
      "sessions": 1,
      "cost": 0.13,
      "tokens": 17108
    },
    {
      "project": "Users Zeria AppData Local Temp ai label bjne69ah",
      "sessions": 1,
      "cost": 0.11,
      "tokens": 13170
    },
    {
      "project": "Users Zeria AppData Local Temp ai label y2ld1z3s",
      "sessions": 1,
      "cost": 0.1,
      "tokens": 12702
    },
    {
      "project": "Users Zeria AppData Local Temp ai label l1i7x4rq",
      "sessions": 1,
      "cost": 0.1,
      "tokens": 49110
    },
    {
      "project": "Users Zeria AppData Local Temp ai label g2yt6xn8",
      "sessions": 1,
      "cost": 0.1,
      "tokens": 12735
    },
    {
      "project": "Users Zeria AppData Local Temp ai label h8cxkrpw",
      "sessions": 1,
      "cost": 0.09,
      "tokens": 11261
    },
    {
      "project": "Users Zeria AppData Local Temp ai label dny6ah5s",
      "sessions": 1,
      "cost": 0.09,
      "tokens": 10804
    },
    {
      "project": "Users Zeria AppData Local Temp ai label ynt tofm",
      "sessions": 1,
      "cost": 0.09,
      "tokens": 11796
    },
    {
      "project": "Users Zeria AppData Local Temp ai label smhnwak9",
      "sessions": 1,
      "cost": 0.09,
      "tokens": 11708
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 246sgsx3",
      "sessions": 1,
      "cost": 0.09,
      "tokens": 23584
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 7wzx042h",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 9595
    },
    {
      "project": "Users Zeria AppData Local Temp ai label w1aq4ndu",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 17133
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 695gzden",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 9503
    },
    {
      "project": "Users Zeria AppData Local Temp ai label sn n990d",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 22534
    },
    {
      "project": "Users Zeria AppData Local Temp ai label nlhltfc6",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 8288
    },
    {
      "project": "Users Zeria AppData Local Temp ai label yxm2610n",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 18056
    },
    {
      "project": "Users Zeria AppData Local Temp ai label oh2wlgb5",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 8234
    },
    {
      "project": "Users Zeria AppData Local Temp ai label atap21rc",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 9031
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 6e0i1o w",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 8671
    },
    {
      "project": "Users Zeria AppData Local Temp ai label tcuau3i7",
      "sessions": 1,
      "cost": 0.07,
      "tokens": 9308
    },
    {
      "project": "Users Zeria AppData Local Temp ai label jygqd7ir",
      "sessions": 1,
      "cost": 0.06,
      "tokens": 7948
    },
    {
      "project": "Users Zeria AppData Local Temp ai label uj1944d7",
      "sessions": 1,
      "cost": 0.06,
      "tokens": 28156
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 204bsswv",
      "sessions": 1,
      "cost": 0.06,
      "tokens": 7306
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 94vl97n2",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12719
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 445zzk55",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 24191
    },
    {
      "project": "Users Zeria AppData Local Temp ai label zo6hoxox",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 6907
    },
    {
      "project": "Users Zeria AppData Local Temp ai label pl8joqlq",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12740
    },
    {
      "project": "Users Zeria AppData Local Temp ai label h4eml9a2",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 13682
    },
    {
      "project": "Users Zeria AppData Local Temp ai label nmud0rcz",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 6914
    },
    {
      "project": "Users Zeria AppData Local Temp ai label llr5l9dj",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12660
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 9oy27h98",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 6627
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 09hvcwbp",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12740
    },
    {
      "project": "Users Zeria AppData Local Temp ai label xl0ulser",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12728
    },
    {
      "project": "Users Zeria AppData Local Temp ai label mbejlqs7",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12726
    },
    {
      "project": "Users Zeria AppData Local Temp ai label sz17p4ck",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12724
    },
    {
      "project": "Users Zeria AppData Local Temp ai label qtrmcv2c",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12704
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 7qk3sddr",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 12753
    },
    {
      "project": "Users Zeria AppData Local Temp ai label klwrs q0",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 13654
    },
    {
      "project": "Users Zeria AppData Local Temp ai label a4tslc6l",
      "sessions": 1,
      "cost": 0.05,
      "tokens": 13045
    },
    {
      "project": "Users Zeria AppData Local Temp ai label n5rwpaq",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 11149
    },
    {
      "project": "Users Zeria AppData Local Temp ai label z8bmabxv",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 10655
    },
    {
      "project": "Users Zeria AppData Local Temp ai label sa504isj",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 9331
    },
    {
      "project": "Users Zeria AppData Local Temp ai label gnc5pq8d",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 9093
    },
    {
      "project": "Users Zeria AppData Local Temp ai label etfrngpq",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 11128
    },
    {
      "project": "Users Zeria AppData Local Temp ai label dgww3cpe",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 16308
    },
    {
      "project": "Users Zeria AppData Local Temp ai label z3n4177v",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 9343
    },
    {
      "project": "Users Zeria AppData Local Temp ai label g u 3et",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 19288
    },
    {
      "project": "Users Zeria AppData Local Temp ai label z 7l2qdu",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 10684
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 4jszvo0t",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 20655
    },
    {
      "project": "Users Zeria AppData Local Temp ai label f5wrc2vj",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 11593
    },
    {
      "project": "Users Zeria AppData Local Temp ai label hv3myv66",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 11159
    },
    {
      "project": "Users Zeria AppData Local Temp ai label y78kt kp",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 11135
    },
    {
      "project": "Users Zeria AppData Local Temp ai label e864o056",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 20075
    },
    {
      "project": "Users Zeria AppData Local Temp ai label jio4r5tj",
      "sessions": 1,
      "cost": 0.04,
      "tokens": 10655
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 5gjhzp7w",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 4528
    },
    {
      "project": "Users Zeria AppData Local Temp ai label r7m83l3z",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 7189
    },
    {
      "project": "Users Zeria AppData Local Temp ai label kfclszh7",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 14413
    },
    {
      "project": "Users Zeria AppData Local Temp ai label yh027tuk",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 6661
    },
    {
      "project": "Users Zeria AppData Local Temp ai label sgfe 5mr",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 8689
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 3oetn8aq",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 8085
    },
    {
      "project": "Users Zeria AppData Local Temp ai label f7t5sws",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 15213
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 2u4sco41",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 8696
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 3v4lkf6j",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 8674
    },
    {
      "project": "Users Zeria AppData Local Temp ai label jz6ybfvh",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 20461
    },
    {
      "project": "Users Zeria AppData Local Temp ai label 6oml 0ca",
      "sessions": 1,
      "cost": 0.03,
      "tokens": 9017
    },
    {
      "project": "Users Zeria AppData Local Temp ai label alkzxh2o",
      "sessions": 1,
      "cost": 0.02,
      "tokens": 5006
    },
    {
      "project": "Users Zeria AppData Local Temp ai label vlvg44l",
      "sessions": 1,
      "cost": 0.02,
      "tokens": 5061
    },
    {
      "project": "Users Zeria AppData Local Temp tmp YuT13MvBlT",
      "sessions": 1,
      "cost": 0.01,
      "tokens": 7104
    }
  ],
  "recent": [
    {
      "id": "caa8d86e",
      "project": "worktree",
      "models": [
        "fable-5-1",
        "opus-5-5",
        "sonnet-5-5"
      ],
      "cost": 23.28,
      "tokens": 12602137,
      "lastActivity": "2026-10-08T08:17:27.646Z"
    },
    {
      "id": "471a4fe0",
      "project": "Team Claude",
      "models": [
        "sonnet-5-5",
        "fable-5-1",
        "opus-5-5"
      ],
      "cost": 33.88,
      "tokens": 43470502,
      "lastActivity": "2026-10-08T08:13:23.480Z"
    },
    {
      "id": "5289657c",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 15.76,
      "tokens": 14378989,
      "lastActivity": "2026-10-08T08:08:46.619Z"
    },
    {
      "id": "1188e7f7",
      "project": "worktree",
      "models": [
        "sonnet-5-5",
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 21.14,
      "tokens": 22389517,
      "lastActivity": "2026-10-08T06:53:48.353Z"
    },
    {
      "id": "f57d6869",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "sonnet-5-5"
      ],
      "cost": 11.61,
      "tokens": 24610985,
      "lastActivity": "2026-10-08T06:33:49.631Z"
    },
    {
      "id": "15a5ebc1",
      "project": "worktree",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 0.02,
      "tokens": 104950,
      "lastActivity": "2026-10-08T04:24:45.188Z"
    },
    {
      "id": "e31c373f",
      "project": "Local Intel",
      "models": [
        "sonnet-5-5",
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 43.69,
      "tokens": 40423034,
      "lastActivity": "2026-10-08T04:12:44.280Z"
    },
    {
      "id": "149dd3e5",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 32.29,
      "tokens": 47431508,
      "lastActivity": "2026-10-08T04:12:43.569Z"
    },
    {
      "id": "e214c1a3",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 4.71,
      "tokens": 8482822,
      "lastActivity": "2026-10-08T04:11:04.618Z"
    },
    {
      "id": "83e37b57",
      "project": "Personal Project Platform",
      "models": [
        "sonnet-5-5",
        "opus-5-5"
      ],
      "cost": 17.48,
      "tokens": 35074022,
      "lastActivity": "2026-10-08T04:07:13.059Z"
    },
    {
      "id": "2141c658",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 4.91,
      "tokens": 10418538,
      "lastActivity": "2026-10-08T03:52:28.226Z"
    },
    {
      "id": "3d75b5eb",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 3.08,
      "tokens": 6688561,
      "lastActivity": "2026-10-08T03:49:46.775Z"
    },
    {
      "id": "f80d473c",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "sonnet-5-5"
      ],
      "cost": 2.32,
      "tokens": 3945665,
      "lastActivity": "2026-10-08T03:49:35.412Z"
    },
    {
      "id": "737ce250",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "sonnet-5-5"
      ],
      "cost": 0.61,
      "tokens": 348506,
      "lastActivity": "2026-10-08T03:45:22.667Z"
    },
    {
      "id": "3323eb00",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 38.45,
      "tokens": 77232550,
      "lastActivity": "2026-10-08T01:19:33.421Z"
    },
    {
      "id": "5e5c1cd8",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 194.45,
      "tokens": 268814984,
      "lastActivity": "2026-10-08T01:19:32.681Z"
    },
    {
      "id": "ec705793",
      "project": "ClickUp AI",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 1.81,
      "tokens": 8147637,
      "lastActivity": "2026-10-08T00:24:38.967Z"
    },
    {
      "id": "6573e356",
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 10 07 9ef885",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 0.22,
      "tokens": 344603,
      "lastActivity": "2026-10-07T23:24:41.897Z"
    },
    {
      "id": "a9162bbc",
      "project": "ClickUp AI",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 0.31,
      "tokens": 1305157,
      "lastActivity": "2026-10-07T22:35:14.433Z"
    },
    {
      "id": "3f973a8e",
      "project": "ClickUp AI",
      "models": [
        "sonnet-5-5",
        "opus-5-5"
      ],
      "cost": 6.17,
      "tokens": 15496969,
      "lastActivity": "2026-10-07T22:29:51.246Z"
    },
    {
      "id": "838982c8",
      "project": "Revit Ops",
      "models": [
        "opus-5-5",
        "sonnet-5-5"
      ],
      "cost": 1.83,
      "tokens": 6081689,
      "lastActivity": "2026-10-07T21:23:15.712Z"
    },
    {
      "id": "a31f1905",
      "project": "worktree",
      "models": [
        "fable-5-1",
        "opus-5-5"
      ],
      "cost": 168,
      "tokens": 151255784,
      "lastActivity": "2026-10-07T20:59:57.839Z"
    },
    {
      "id": "a660809c",
      "project": "Revit Ops",
      "models": [
        "opus-5-5"
      ],
      "cost": 1.92,
      "tokens": 2764220,
      "lastActivity": "2026-10-07T15:16:00.692Z"
    },
    {
      "id": "ad58d442",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 13.7,
      "tokens": 26985719,
      "lastActivity": "2026-10-07T07:11:05.318Z"
    },
    {
      "id": "9fe6b900",
      "project": "AI Dashboard",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 1.62,
      "tokens": 4102726,
      "lastActivity": "2026-10-07T06:38:59.581Z"
    },
    {
      "id": "7ed14227",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 40.9,
      "tokens": 74871786,
      "lastActivity": "2026-10-07T06:27:48.643Z"
    },
    {
      "id": "a6e4ebc0",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 5.71,
      "tokens": 10931264,
      "lastActivity": "2026-10-07T06:14:15.425Z"
    },
    {
      "id": "45edefc2",
      "project": "Users Zeria AppData Local Temp ai label sn n990d",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.07,
      "tokens": 22534,
      "lastActivity": "2026-10-07T06:12:25.459Z"
    },
    {
      "id": "8f7275e8",
      "project": "Users Zeria AppData Local Temp ai label p92rrsyu",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.31,
      "tokens": 152035,
      "lastActivity": "2026-10-07T06:11:55.010Z"
    },
    {
      "id": "4a14c61d",
      "project": "Users Zeria AppData Local Temp ai label kfclszh7",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.03,
      "tokens": 14413,
      "lastActivity": "2026-10-07T06:11:48.145Z"
    }
  ],
  "timeline": [
    {
      "date": "2026-09-11",
      "cost": 320.25,
      "sessions": 14
    },
    {
      "date": "2026-09-12",
      "cost": 321.08,
      "sessions": 25
    },
    {
      "date": "2026-09-13",
      "cost": 329.75,
      "sessions": 28
    },
    {
      "date": "2026-09-14",
      "cost": 56.62,
      "sessions": 13
    },
    {
      "date": "2026-09-16",
      "cost": 548.38,
      "sessions": 5
    },
    {
      "date": "2026-09-19",
      "cost": 0.27,
      "sessions": 0
    },
    {
      "date": "2026-09-20",
      "cost": 63.89,
      "sessions": 1
    },
    {
      "date": "2026-09-21",
      "cost": 395.2,
      "sessions": 0
    },
    {
      "date": "2026-09-22",
      "cost": 247.01,
      "sessions": 15
    },
    {
      "date": "2026-09-23",
      "cost": 475.68,
      "sessions": 13
    },
    {
      "date": "2026-09-24",
      "cost": 606.09,
      "sessions": 25
    },
    {
      "date": "2026-09-25",
      "cost": 347.56,
      "sessions": 17
    },
    {
      "date": "2026-09-26",
      "cost": 412.12,
      "sessions": 24
    },
    {
      "date": "2026-09-28",
      "cost": 18.45,
      "sessions": 0
    },
    {
      "date": "2026-09-29",
      "cost": 274.66,
      "sessions": 4
    },
    {
      "date": "2026-09-30",
      "cost": 53.04,
      "sessions": 17
    },
    {
      "date": "2026-10-01",
      "cost": 82.57,
      "sessions": 0
    },
    {
      "date": "2026-10-05",
      "cost": 672.04,
      "sessions": 8
    },
    {
      "date": "2026-10-06",
      "cost": 683.45,
      "sessions": 29
    },
    {
      "date": "2026-10-07",
      "cost": 291.79,
      "sessions": 133
    },
    {
      "date": "2026-10-08",
      "cost": 44.89,
      "sessions": 17
    }
  ],
  "health": {
    "cacheHitRate": 95,
    "errorRate": 4.3,
    "avgCostPerSession": 23.57,
    "avgTokensPerSession": 25085313,
    "toolCalls": 7166,
    "errors": 309,
    "scannedSessions": 120,
    "bounded": false,
    "modelMix": [
      {
        "model": "opus-4-8",
        "cost": 6204.63,
        "pct": 27
      },
      {
        "model": "fable-5",
        "cost": 5579.67,
        "pct": 24
      },
      {
        "model": "opus-5",
        "cost": 3474.15,
        "pct": 15
      },
      {
        "model": "fable-5-1",
        "cost": 2879.89,
        "pct": 12
      },
      {
        "model": "sonnet-5",
        "cost": 2481.97,
        "pct": 11
      },
      {
        "model": "opus-5-5",
        "cost": 2456.75,
        "pct": 11
      },
      {
        "model": "sonnet-5-5",
        "cost": 88.5,
        "pct": 0
      },
      {
        "model": "sonnet-4-6",
        "cost": 49.67,
        "pct": 0
      },
      {
        "model": "haiku-4-5",
        "cost": 3.27,
        "pct": 0
      },
      {
        "model": "qwen3-coder-32k",
        "cost": 0.54,
        "pct": 0
      },
      {
        "model": "qwen3-coder:30b-a3b-q4_K_M",
        "cost": 0.02,
        "pct": 0
      },
      {
        "model": "qwen2.5-coder:14b",
        "cost": 0,
        "pct": 0
      }
    ]
  },
  "tools": [
    {
      "name": "Bash",
      "count": 3904,
      "pct": 54
    },
    {
      "name": "PowerShell",
      "count": 664,
      "pct": 9
    },
    {
      "name": "Edit",
      "count": 556,
      "pct": 8
    },
    {
      "name": "Read",
      "count": 524,
      "pct": 7
    },
    {
      "name": "Write",
      "count": 479,
      "pct": 7
    },
    {
      "name": "Grep",
      "count": 263,
      "pct": 4
    },
    {
      "name": "Agent",
      "count": 255,
      "pct": 4
    },
    {
      "name": "SendUserFile",
      "count": 126,
      "pct": 2
    },
    {
      "name": "mcp__mcp-server-for-revit__send_code_to_revit",
      "count": 71,
      "pct": 1
    },
    {
      "name": "ToolSearch",
      "count": 59,
      "pct": 1
    },
    {
      "name": "SendMessage",
      "count": 43,
      "pct": 1
    },
    {
      "name": "mcp__claude-in-chrome__computer",
      "count": 35,
      "pct": 0
    },
    {
      "name": "StructuredOutput",
      "count": 23,
      "pct": 0
    },
    {
      "name": "TaskStop",
      "count": 20,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__browser_batch",
      "count": 20,
      "pct": 0
    },
    {
      "name": "Monitor",
      "count": 17,
      "pct": 0
    },
    {
      "name": "ListAgents",
      "count": 11,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__search_session_transcripts",
      "count": 10,
      "pct": 0
    },
    {
      "name": "ReadNotifications",
      "count": 10,
      "pct": 0
    },
    {
      "name": "WebFetch",
      "count": 9,
      "pct": 0
    },
    {
      "name": "Glob",
      "count": 8,
      "pct": 0
    },
    {
      "name": "Skill",
      "count": 7,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__find",
      "count": 7,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__tabs_context_mcp",
      "count": 6,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__navigate",
      "count": 4,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__dismiss_task",
      "count": 4,
      "pct": 0
    },
    {
      "name": "WebSearch",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__spawn_task",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__javascript_tool",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__ccd_pr__get_status",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__mark_chapter",
      "count": 2,
      "pct": 0
    },
    {
      "name": "EnterWorktree",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__list_sessions",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__resize_window",
      "count": 2,
      "pct": 0
    },
    {
      "name": "ReportFindings",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__list_connected_browsers",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__get_page_text",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__form_input",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__autodesk-revit-2027__get_running_revit_instances",
      "count": 1,
      "pct": 0
    },
    {
      "name": "AskUserQuestion",
      "count": 1,
      "pct": 0
    },
    {
      "name": "ScheduleWakeup",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__navigate",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__update_scheduled_task",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__get_session",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__list_events",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__javascript_tool",
      "count": 1,
      "pct": 0
    }
  ],
  "subagents": {
    "total": 258,
    "byProject": [
      {
        "project": "worktree",
        "count": 229
      },
      {
        "project": "AI Dashboard",
        "count": 15
      },
      {
        "project": "Team Claude",
        "count": 6
      },
      {
        "project": "Local Intel",
        "count": 4
      },
      {
        "project": "Personal Project Platform",
        "count": 4
      }
    ],
    "scannedSessions": 120,
    "bounded": false
  },
  "workflow": {
    "subagentTypes": [
      {
        "type": "general-purpose",
        "count": 189
      },
      {
        "type": "security-engineer",
        "count": 26
      },
      {
        "type": "Explore",
        "count": 13
      },
      {
        "type": "pr-review-toolkit:code-reviewer",
        "count": 9
      },
      {
        "type": "backend-endpoint-reviewer",
        "count": 8
      },
      {
        "type": "qa-engineer",
        "count": 7
      },
      {
        "type": "web-fetch",
        "count": 3
      },
      {
        "type": "migration-reviewer",
        "count": 1
      },
      {
        "type": "typescript-api-reviewer",
        "count": 1
      },
      {
        "type": "pr-review-toolkit:silent-failure-hunter",
        "count": 1
      }
    ],
    "avgSubagentsPerSession": 2.15,
    "successRate": 95.7,
    "topSubagentType": "general-purpose",
    "mostCommonTool": "Bash"
  },
  "analytics": {
    "totalSessions": 985,
    "totalTokens": 24709033023,
    "totalCost": 23219.07,
    "events": 75698,
    "byWeekday": [
      {
        "day": "Sun",
        "cost": 3835.93
      },
      {
        "day": "Mon",
        "cost": 3519.89
      },
      {
        "day": "Tue",
        "cost": 4174.15
      },
      {
        "day": "Wed",
        "cost": 3316.01
      },
      {
        "day": "Thu",
        "cost": 2434.61
      },
      {
        "day": "Fri",
        "cost": 2825.81
      },
      {
        "day": "Sat",
        "cost": 3112.68
      }
    ]
  },
  "config": {
    "skills": 17,
    "subagents": 8,
    "commands": 0,
    "outputStyles": 0,
    "plugins": 8,
    "mcpServers": 0,
    "hooks": 11,
    "keybindings": 0,
    "memory": 541
  },
  "recentEvents": [
    {
      "ts": "2026-10-08T08:17:13.729Z",
      "tool": "SendUserFile",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:17:09.051Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:16:52.168Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:16:43.607Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:16:37.110Z",
      "tool": "Write",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:16:18.873Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:16:15.468Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:16:10.654Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:13:14.410Z",
      "tool": "SendUserFile",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:13:11.681Z",
      "tool": "Write",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:49.563Z",
      "tool": "PowerShell",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:47.779Z",
      "tool": "PowerShell",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:12:41.857Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:12:41.507Z",
      "tool": "Bash",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:37.788Z",
      "tool": "PowerShell",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:30.726Z",
      "tool": "PowerShell",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:30.097Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:12:26.630Z",
      "tool": "Write",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:24.456Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "caa8d86e"
    },
    {
      "ts": "2026-10-08T08:12:16.655Z",
      "tool": "Grep",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:15.758Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:09.207Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:04.970Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:12:01.673Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:11:59.722Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:11:47.749Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:11:45.124Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:11:42.472Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:11:39.517Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:11:33.204Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:11:00.239Z",
      "tool": "Read",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:59.630Z",
      "tool": "Read",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:50.222Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:44.026Z",
      "tool": "Read",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:36.159Z",
      "tool": "PowerShell",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:25.484Z",
      "tool": "PowerShell",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:19.125Z",
      "tool": "PowerShell",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:17.737Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:15.420Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    },
    {
      "ts": "2026-10-08T08:09:13.670Z",
      "tool": "Edit",
      "project": "Team Claude",
      "session": "471a4fe0"
    }
  ]
};
