// Auto-generated by agents_sync.mjs — Claude Code session/agent activity.
// Native (no server, no ~/.claude hooks). Cost = API-equivalent. Do not hand-edit.
window.DASHBOARD_AGENTS = {
  "generated": "2026-10-07T03:19:16.519Z",
  "source": "ccusage + ~/.claude/projects (native, no hooks)",
  "totals": {
    "sessions": 858,
    "cost": 22719.95,
    "tokens": 23956405803,
    "activeToday": 46,
    "active7d": 73,
    "projects": 33
  },
  "byProject": [
    {
      "project": "worktree",
      "sessions": 326,
      "cost": 7155.28,
      "tokens": 8322940098
    },
    {
      "project": "BIMpossible",
      "sessions": 148,
      "cost": 4788.39,
      "tokens": 4161231964
    },
    {
      "project": "BIMpossible Workspace",
      "sessions": 127,
      "cost": 4550.93,
      "tokens": 4666746601
    },
    {
      "project": "AI Dev",
      "sessions": 112,
      "cost": 2543.5,
      "tokens": 2035576992
    },
    {
      "project": "Add Ins",
      "sessions": 19,
      "cost": 935.09,
      "tokens": 1314664558
    },
    {
      "project": "AI Models Local",
      "sessions": 12,
      "cost": 725.42,
      "tokens": 719353787
    },
    {
      "project": "AI Dashboard",
      "sessions": 25,
      "cost": 616.52,
      "tokens": 778248836
    },
    {
      "project": "Families by BIMpossible",
      "sessions": 5,
      "cost": 313.46,
      "tokens": 300307482
    },
    {
      "project": "Dashboard",
      "sessions": 4,
      "cost": 250.71,
      "tokens": 439468566
    },
    {
      "project": "BIMpossible Site",
      "sessions": 6,
      "cost": 200.86,
      "tokens": 317010540
    },
    {
      "project": "Evidence Compiler",
      "sessions": 5,
      "cost": 148.3,
      "tokens": 143749255
    },
    {
      "project": "F--",
      "sessions": 6,
      "cost": 66.28,
      "tokens": 96813869
    },
    {
      "project": "(unknown)",
      "sessions": 7,
      "cost": 47.45,
      "tokens": 32071794
    },
    {
      "project": "Claude Profile",
      "sessions": 4,
      "cost": 46.77,
      "tokens": 75670418
    },
    {
      "project": "Claude Tools",
      "sessions": 6,
      "cost": 43.95,
      "tokens": 95583803
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 12 43737e",
      "sessions": 4,
      "cost": 38.58,
      "tokens": 43922078
    },
    {
      "project": "AI Server",
      "sessions": 3,
      "cost": 38.37,
      "tokens": 90178047
    },
    {
      "project": "Revit Ops",
      "sessions": 7,
      "cost": 28.65,
      "tokens": 54169694
    },
    {
      "project": "Finance Dashboard",
      "sessions": 1,
      "cost": 28.12,
      "tokens": 55931041
    },
    {
      "project": "My Drive Coord Desktop AI ClickUp and Claude",
      "sessions": 8,
      "cost": 27.02,
      "tokens": 52823122
    },
    {
      "project": "Claude Tools graphify",
      "sessions": 5,
      "cost": 25.31,
      "tokens": 48992135
    },
    {
      "project": "YourBIMpossible",
      "sessions": 1,
      "cost": 19.51,
      "tokens": 22212496
    },
    {
      "project": "Preseason Pick em",
      "sessions": 3,
      "cost": 17.3,
      "tokens": 18097209
    },
    {
      "project": "Local Intel",
      "sessions": 1,
      "cost": 11.98,
      "tokens": 20322254
    },
    {
      "project": "PC Monitor",
      "sessions": 1,
      "cost": 11.1,
      "tokens": 14935550
    },
    {
      "project": "BIMpossible AddIns",
      "sessions": 3,
      "cost": 8.7,
      "tokens": 6195057
    },
    {
      "project": "zCSuite Artifacts",
      "sessions": 1,
      "cost": 8.63,
      "tokens": 2675564
    },
    {
      "project": "D--",
      "sessions": 2,
      "cost": 6.53,
      "tokens": 10412308
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 21 aa524b",
      "sessions": 1,
      "cost": 6.28,
      "tokens": 5276442
    },
    {
      "project": "Users Zeria Downloads",
      "sessions": 1,
      "cost": 3.17,
      "tokens": 2101528
    },
    {
      "project": "Users Zeria AppData Roaming Claude scratch workspaces 37b01c58 1652 424c aa49 ee3fcfae18ed 4a476cdb 8db4 46b9 b7e0 796859db18aa scratch 2026 09 07 6a6ce1",
      "sessions": 1,
      "cost": 3.06,
      "tokens": 1893084
    },
    {
      "project": "Users Zeria AppData Local Programs OpenWhispr",
      "sessions": 1,
      "cost": 2.3,
      "tokens": 5711812
    },
    {
      "project": "Brother",
      "sessions": 2,
      "cost": 2.19,
      "tokens": 1117819
    }
  ],
  "recent": [
    {
      "id": "5e5c1cd8",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 91.9,
      "tokens": 72522203,
      "lastActivity": "2026-10-07T03:19:10.059Z"
    },
    {
      "id": "cfe5bbc0",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1",
        "sonnet-5-5"
      ],
      "cost": 159.87,
      "tokens": 295605208,
      "lastActivity": "2026-10-07T03:19:02.144Z"
    },
    {
      "id": "a31f1905",
      "project": "worktree",
      "models": [
        "fable-5-1"
      ],
      "cost": 133.61,
      "tokens": 106761186,
      "lastActivity": "2026-10-07T03:19:01.030Z"
    },
    {
      "id": "1906cff0",
      "project": "AI Dashboard",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 16.84,
      "tokens": 53580358,
      "lastActivity": "2026-10-07T03:18:51.366Z"
    },
    {
      "id": "3a91560c",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 17.23,
      "tokens": 33703385,
      "lastActivity": "2026-10-07T03:18:49.095Z"
    },
    {
      "id": "5035df89",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 6.05,
      "tokens": 15865583,
      "lastActivity": "2026-10-07T03:18:05.601Z"
    },
    {
      "id": "06de143b",
      "project": "BIMpossible Workspace",
      "models": [
        "opus-5-5"
      ],
      "cost": 6.35,
      "tokens": 12993069,
      "lastActivity": "2026-10-07T03:17:11.704Z"
    },
    {
      "id": "253c4d7c",
      "project": "worktree",
      "models": [
        "fable-5-1"
      ],
      "cost": 1.45,
      "tokens": 72359,
      "lastActivity": "2026-10-07T03:13:20.627Z"
    },
    {
      "id": "1eea6c68",
      "project": "worktree",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 0.28,
      "tokens": 70510,
      "lastActivity": "2026-10-07T03:13:06.365Z"
    },
    {
      "id": "27198a14",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 0.56,
      "tokens": 70496,
      "lastActivity": "2026-10-07T03:12:57.919Z"
    },
    {
      "id": "7ed14227",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 23.75,
      "tokens": 43031573,
      "lastActivity": "2026-10-07T03:08:54.797Z"
    },
    {
      "id": "48f97ff8",
      "project": "worktree",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 0.22,
      "tokens": 331599,
      "lastActivity": "2026-10-07T02:37:40.109Z"
    },
    {
      "id": "958de852",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 7.7,
      "tokens": 14374931,
      "lastActivity": "2026-10-07T02:20:08.255Z"
    },
    {
      "id": "3cef6a97",
      "project": "AI Dashboard",
      "models": [
        "sonnet-5-5",
        "opus-5-5"
      ],
      "cost": 36.73,
      "tokens": 103348107,
      "lastActivity": "2026-10-07T02:01:41.452Z"
    },
    {
      "id": "29d4ab03",
      "project": "My Drive Coord Desktop AI ClickUp and Claude",
      "models": [
        "sonnet-5-5",
        "opus-5-5"
      ],
      "cost": 4.68,
      "tokens": 10298831,
      "lastActivity": "2026-10-07T00:49:13.057Z"
    },
    {
      "id": "852dbed0",
      "project": "worktree",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.06,
      "tokens": 114443,
      "lastActivity": "2026-10-07T00:03:50.430Z"
    },
    {
      "id": "9bbc26d0",
      "project": "worktree",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.12,
      "tokens": 115886,
      "lastActivity": "2026-10-07T00:03:37.022Z"
    },
    {
      "id": "0330e48b",
      "project": "worktree",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.06,
      "tokens": 114350,
      "lastActivity": "2026-10-07T00:02:44.797Z"
    },
    {
      "id": "59997391",
      "project": "worktree",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.07,
      "tokens": 116712,
      "lastActivity": "2026-10-07T00:02:32.176Z"
    },
    {
      "id": "dca71ce6",
      "project": "worktree",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.07,
      "tokens": 116559,
      "lastActivity": "2026-10-07T00:02:03.445Z"
    },
    {
      "id": "4edb47e9",
      "project": "worktree",
      "models": [
        "haiku-4-5"
      ],
      "cost": 0.12,
      "tokens": 56873,
      "lastActivity": "2026-10-07T00:01:29.019Z"
    },
    {
      "id": "98804545",
      "project": "worktree",
      "models": [
        "opus-5-5",
        "fable-5-1"
      ],
      "cost": 155.08,
      "tokens": 240379171,
      "lastActivity": "2026-10-06T23:51:59.996Z"
    },
    {
      "id": "35b75269",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 29.37,
      "tokens": 56761346,
      "lastActivity": "2026-10-06T23:35:40.492Z"
    },
    {
      "id": "ce0c0702",
      "project": "worktree",
      "models": [
        "sonnet-5-5"
      ],
      "cost": 1.2,
      "tokens": 1982188,
      "lastActivity": "2026-10-06T22:56:25.926Z"
    },
    {
      "id": "51f7974b",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 81.99,
      "tokens": 171033229,
      "lastActivity": "2026-10-06T22:28:37.016Z"
    },
    {
      "id": "9fde6c4a",
      "project": "worktree",
      "models": [
        "opus-5-5"
      ],
      "cost": 9.56,
      "tokens": 16696043,
      "lastActivity": "2026-10-06T21:45:13.990Z"
    },
    {
      "id": "95f73e3d",
      "project": "BIMpossible Workspace",
      "models": [
        "opus-5-5"
      ],
      "cost": 13.21,
      "tokens": 24945961,
      "lastActivity": "2026-10-06T21:29:24.551Z"
    },
    {
      "id": "a660809c",
      "project": "Revit Ops",
      "models": [
        "opus-5-5"
      ],
      "cost": 0.81,
      "tokens": 2269958,
      "lastActivity": "2026-10-06T20:49:26.711Z"
    },
    {
      "id": "19593be9",
      "project": "My Drive Coord Desktop AI ClickUp and Claude",
      "models": [
        "opus-5-5",
        "sonnet-5-5"
      ],
      "cost": 6.25,
      "tokens": 13557462,
      "lastActivity": "2026-10-06T20:24:00.437Z"
    },
    {
      "id": "71b4e731",
      "project": "Revit Ops",
      "models": [
        "opus-5-5"
      ],
      "cost": 3.17,
      "tokens": 5745467,
      "lastActivity": "2026-10-06T20:11:49.091Z"
    }
  ],
  "timeline": [
    {
      "date": "2026-09-07",
      "cost": 408.37,
      "sessions": 30
    },
    {
      "date": "2026-09-10",
      "cost": 226.89,
      "sessions": 0
    },
    {
      "date": "2026-09-11",
      "cost": 320.25,
      "sessions": 14
    },
    {
      "date": "2026-09-12",
      "cost": 321.08,
      "sessions": 25
    },
    {
      "date": "2026-09-13",
      "cost": 329.75,
      "sessions": 28
    },
    {
      "date": "2026-09-14",
      "cost": 56.62,
      "sessions": 13
    },
    {
      "date": "2026-09-16",
      "cost": 548.38,
      "sessions": 5
    },
    {
      "date": "2026-09-19",
      "cost": 0.27,
      "sessions": 0
    },
    {
      "date": "2026-09-20",
      "cost": 63.89,
      "sessions": 1
    },
    {
      "date": "2026-09-21",
      "cost": 395.2,
      "sessions": 0
    },
    {
      "date": "2026-09-22",
      "cost": 247.01,
      "sessions": 15
    },
    {
      "date": "2026-09-23",
      "cost": 475.68,
      "sessions": 13
    },
    {
      "date": "2026-09-24",
      "cost": 606.09,
      "sessions": 25
    },
    {
      "date": "2026-09-25",
      "cost": 347.56,
      "sessions": 17
    },
    {
      "date": "2026-09-26",
      "cost": 412.12,
      "sessions": 24
    },
    {
      "date": "2026-09-28",
      "cost": 18.45,
      "sessions": 0
    },
    {
      "date": "2026-09-29",
      "cost": 274.66,
      "sessions": 4
    },
    {
      "date": "2026-09-30",
      "cost": 53.04,
      "sessions": 17
    },
    {
      "date": "2026-10-01",
      "cost": 82.57,
      "sessions": 0
    },
    {
      "date": "2026-10-05",
      "cost": 676.33,
      "sessions": 8
    },
    {
      "date": "2026-10-06",
      "cost": 516.78,
      "sessions": 31
    }
  ],
  "health": {
    "cacheHitRate": 96,
    "errorRate": 4.7,
    "avgCostPerSession": 26.48,
    "avgTokensPerSession": 27921219,
    "toolCalls": 13191,
    "errors": 620,
    "scannedSessions": 73,
    "bounded": false,
    "modelMix": [
      {
        "model": "opus-4-8",
        "cost": 6204.63,
        "pct": 27
      },
      {
        "model": "fable-5",
        "cost": 5579.67,
        "pct": 25
      },
      {
        "model": "opus-5",
        "cost": 3474.15,
        "pct": 15
      },
      {
        "model": "fable-5-1",
        "cost": 2718.94,
        "pct": 12
      },
      {
        "model": "sonnet-5",
        "cost": 2481.24,
        "pct": 11
      },
      {
        "model": "opus-5-5",
        "cost": 2143.61,
        "pct": 9
      },
      {
        "model": "sonnet-5-5",
        "cost": 64.65,
        "pct": 0
      },
      {
        "model": "sonnet-4-6",
        "cost": 49.67,
        "pct": 0
      },
      {
        "model": "haiku-4-5",
        "cost": 2.82,
        "pct": 0
      },
      {
        "model": "qwen3-coder-32k",
        "cost": 0.54,
        "pct": 0
      },
      {
        "model": "qwen3-coder:30b-a3b-q4_K_M",
        "cost": 0.02,
        "pct": 0
      },
      {
        "model": "qwen2.5-coder:14b",
        "cost": 0,
        "pct": 0
      }
    ]
  },
  "tools": [
    {
      "name": "Bash",
      "count": 8392,
      "pct": 64
    },
    {
      "name": "Edit",
      "count": 955,
      "pct": 7
    },
    {
      "name": "PowerShell",
      "count": 763,
      "pct": 6
    },
    {
      "name": "Write",
      "count": 697,
      "pct": 5
    },
    {
      "name": "Read",
      "count": 611,
      "pct": 5
    },
    {
      "name": "Agent",
      "count": 405,
      "pct": 3
    },
    {
      "name": "SendUserFile",
      "count": 254,
      "pct": 2
    },
    {
      "name": "Grep",
      "count": 188,
      "pct": 1
    },
    {
      "name": "ToolSearch",
      "count": 158,
      "pct": 1
    },
    {
      "name": "mcp__claude-in-chrome__browser_batch",
      "count": 148,
      "pct": 1
    },
    {
      "name": "mcp__mcp-server-for-revit__send_code_to_revit",
      "count": 136,
      "pct": 1
    },
    {
      "name": "SendMessage",
      "count": 54,
      "pct": 0
    },
    {
      "name": "Glob",
      "count": 29,
      "pct": 0
    },
    {
      "name": "ListAgents",
      "count": 26,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__computer",
      "count": 24,
      "pct": 0
    },
    {
      "name": "TaskStop",
      "count": 23,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__search_session_transcripts",
      "count": 23,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__list_sessions",
      "count": 20,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__send_message",
      "count": 18,
      "pct": 0
    },
    {
      "name": "Monitor",
      "count": 17,
      "pct": 0
    },
    {
      "name": "Skill",
      "count": 16,
      "pct": 0
    },
    {
      "name": "ReadNotifications",
      "count": 13,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__get_session",
      "count": 13,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__find",
      "count": 12,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__spawn_task",
      "count": 11,
      "pct": 0
    },
    {
      "name": "WebFetch",
      "count": 10,
      "pct": 0
    },
    {
      "name": "AskUserQuestion",
      "count": 9,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__navigate",
      "count": 9,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__tabs_close_mcp",
      "count": 9,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__tabs_context_mcp",
      "count": 8,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__dismiss_task",
      "count": 7,
      "pct": 0
    },
    {
      "name": "ReportFindings",
      "count": 7,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__update_draft",
      "count": 7,
      "pct": 0
    },
    {
      "name": "mcp__ccd_pr__get_status",
      "count": 6,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__update_scheduled_task",
      "count": 6,
      "pct": 0
    },
    {
      "name": "WebSearch",
      "count": 6,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__javascript_tool",
      "count": 6,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__list_scheduled_tasks",
      "count": 5,
      "pct": 0
    },
    {
      "name": "ScheduleWakeup",
      "count": 5,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__get_draft",
      "count": 5,
      "pct": 0
    },
    {
      "name": "mcp__ccd_directory__change_directory",
      "count": 4,
      "pct": 0
    },
    {
      "name": "mcp__20383961-fbf4-4d3a-8451-56c2c20bf0e0__clickup_search",
      "count": 4,
      "pct": 0
    },
    {
      "name": "mcp__ccd_directory__request_directory",
      "count": 4,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__list_events",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__form_input",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__request_access",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__terminal__run_in_terminal",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__screenshot",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__get_page_text",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__autodesk-revit-2027__get_running_revit_instances",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__plugin_context7_context7__query-docs",
      "count": 3,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session__mark_chapter",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__list_task_runs",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__terminal__read_terminal",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__open_application",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__list_connected_browsers",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__create_draft",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__navigate",
      "count": 2,
      "pct": 0
    },
    {
      "name": "EnterWorktree",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__20383961-fbf4-4d3a-8451-56c2c20bf0e0__clickup_get_operators",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__20383961-fbf4-4d3a-8451-56c2c20bf0e0__clickup_get_workspace_hierarchy",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__computer_batch",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__ccd_pr__set_auto_merge",
      "count": 2,
      "pct": 0
    },
    {
      "name": "mcp__scheduled-tasks__create_scheduled_task",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__stop_session",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__ccd_session_mgmt__archive_session",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__terminal__stop_terminal_tab",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__wait",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__read_page",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__javascript_tool",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__tabs_close",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__mcp-server-for-revit__get_current_view_info",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__e9aed87f-8597-434d-b884-5afe680e7018__send_message",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__20383961-fbf4-4d3a-8451-56c2c20bf0e0__clickup_get_list",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__20383961-fbf4-4d3a-8451-56c2c20bf0e0__clickup_get_custom_fields",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__20383961-fbf4-4d3a-8451-56c2c20bf0e0__clickup_filter_tasks",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__20383961-fbf4-4d3a-8451-56c2c20bf0e0__clickup_get_task",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__plugin_context7_context7__resolve-library-id",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__computer",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__tabs_context",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__Claude_Browser__tabs_select",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__claude-in-chrome__read_network_requests",
      "count": 1,
      "pct": 0
    },
    {
      "name": "mcp__computer-use__zoom",
      "count": 1,
      "pct": 0
    }
  ],
  "subagents": {
    "total": 416,
    "byProject": [
      {
        "project": "worktree",
        "count": 292
      },
      {
        "project": "BIMpossible",
        "count": 76
      },
      {
        "project": "AI Dashboard",
        "count": 35
      },
      {
        "project": "F--",
        "count": 8
      },
      {
        "project": "BIMpossible Workspace",
        "count": 3
      },
      {
        "project": "My Drive Coord Desktop AI ClickUp and Claude",
        "count": 2
      }
    ],
    "scannedSessions": 73,
    "bounded": false
  },
  "workflow": {
    "subagentTypes": [
      {
        "type": "general-purpose",
        "count": 315
      },
      {
        "type": "security-engineer",
        "count": 34
      },
      {
        "type": "Explore",
        "count": 29
      },
      {
        "type": "pr-review-toolkit:code-reviewer",
        "count": 19
      },
      {
        "type": "backend-endpoint-reviewer",
        "count": 6
      },
      {
        "type": "qa-engineer",
        "count": 5
      },
      {
        "type": "web-fetch",
        "count": 3
      },
      {
        "type": "typescript-api-reviewer",
        "count": 3
      },
      {
        "type": "migration-reviewer",
        "count": 1
      },
      {
        "type": "pr-review-toolkit:silent-failure-hunter",
        "count": 1
      }
    ],
    "avgSubagentsPerSession": 5.7,
    "successRate": 95.3,
    "topSubagentType": "general-purpose",
    "mostCommonTool": "Bash"
  },
  "analytics": {
    "totalSessions": 858,
    "totalTokens": 23956405803,
    "totalCost": 22719.95,
    "events": 136041,
    "byWeekday": [
      {
        "day": "Sun",
        "cost": 3835.93
      },
      {
        "day": "Mon",
        "cost": 3524.18
      },
      {
        "day": "Tue",
        "cost": 4007.47
      },
      {
        "day": "Wed",
        "cost": 3024.22
      },
      {
        "day": "Thu",
        "cost": 2389.72
      },
      {
        "day": "Fri",
        "cost": 2825.81
      },
      {
        "day": "Sat",
        "cost": 3112.68
      }
    ]
  },
  "config": {
    "skills": 17,
    "subagents": 8,
    "commands": 0,
    "outputStyles": 0,
    "plugins": 8,
    "mcpServers": 0,
    "hooks": 11,
    "keybindings": 0,
    "memory": 540
  },
  "recentEvents": [
    {
      "ts": "2026-10-07T03:19:02.380Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:19:01.877Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5e5c1cd8"
    },
    {
      "ts": "2026-10-07T03:19:01.030Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "a31f1905"
    },
    {
      "ts": "2026-10-07T03:18:58.659Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:18:57.333Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "a31f1905"
    },
    {
      "ts": "2026-10-07T03:18:52.417Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    },
    {
      "ts": "2026-10-07T03:18:51.837Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "a31f1905"
    },
    {
      "ts": "2026-10-07T03:18:46.530Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    },
    {
      "ts": "2026-10-07T03:18:44.019Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5e5c1cd8"
    },
    {
      "ts": "2026-10-07T03:18:42.295Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "a31f1905"
    },
    {
      "ts": "2026-10-07T03:18:38.598Z",
      "tool": "SendUserFile",
      "project": "worktree",
      "session": "3a91560c"
    },
    {
      "ts": "2026-10-07T03:18:38.015Z",
      "tool": "Write",
      "project": "worktree",
      "session": "3a91560c"
    },
    {
      "ts": "2026-10-07T03:18:31.590Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5e5c1cd8"
    },
    {
      "ts": "2026-10-07T03:18:27.682Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:18:21.613Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5e5c1cd8"
    },
    {
      "ts": "2026-10-07T03:18:21.131Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:18:19.108Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3a91560c"
    },
    {
      "ts": "2026-10-07T03:18:18.527Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5e5c1cd8"
    },
    {
      "ts": "2026-10-07T03:18:16.829Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:18:12.666Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    },
    {
      "ts": "2026-10-07T03:18:12.110Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3a91560c"
    },
    {
      "ts": "2026-10-07T03:18:11.891Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5e5c1cd8"
    },
    {
      "ts": "2026-10-07T03:18:06.543Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5e5c1cd8"
    },
    {
      "ts": "2026-10-07T03:18:06.350Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:18:04.567Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    },
    {
      "ts": "2026-10-07T03:18:01.969Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "3a91560c"
    },
    {
      "ts": "2026-10-07T03:18:01.566Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:17:58.180Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5e5c1cd8"
    },
    {
      "ts": "2026-10-07T03:17:56.886Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    },
    {
      "ts": "2026-10-07T03:17:56.741Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:17:50.721Z",
      "tool": "SendUserFile",
      "project": "worktree",
      "session": "5035df89"
    },
    {
      "ts": "2026-10-07T03:17:50.573Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:17:50.059Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    },
    {
      "ts": "2026-10-07T03:17:46.829Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5035df89"
    },
    {
      "ts": "2026-10-07T03:17:46.181Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    },
    {
      "ts": "2026-10-07T03:17:45.582Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "cfe5bbc0"
    },
    {
      "ts": "2026-10-07T03:17:43.934Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5035df89"
    },
    {
      "ts": "2026-10-07T03:17:42.167Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    },
    {
      "ts": "2026-10-07T03:17:40.642Z",
      "tool": "Bash",
      "project": "worktree",
      "session": "5035df89"
    },
    {
      "ts": "2026-10-07T03:17:38.293Z",
      "tool": "Bash",
      "project": "AI Dashboard",
      "session": "1906cff0"
    }
  ]
};
