// bimwatch-panel.js — the BIM-Watch view for the dashboard.
//
// Kept out of index.html on purpose: that file is already ~3000 lines, and this panel
// is a self-contained feature with its own styles, search and chat. index.html only
// needs the four-line wiring (script tag, nav item, show() branch, valid-tab list).
//
// Data comes from window.DASHBOARD_BIMWATCH (bimwatch.js, generated by bimwatch/run.py).
// Deep search lazily fetches bimwatch-archive.json; chat POSTs to /api/bimwatch-chat.
(function () {
  'use strict';

  const TIERS = {
    alert: { label: 'Needs attention', color: 'var(--status-danger)' },
    learn: { label: 'Worth learning', color: 'var(--w2)' },
    fyi: { label: 'Context', color: 'var(--status-info)' },
    unsorted: { label: 'Not yet triaged', color: 'var(--status-dim)' },
    noise: { label: 'Filtered out', color: 'var(--status-dim)' }
  };

  const style = document.createElement('style');
  style.textContent = `
  .bw-head{display:flex;align-items:baseline;gap:var(--sp-3);flex-wrap:wrap;margin-bottom:var(--sp-2);}
  .bw-headline{font-size:var(--ts-md);font-weight:600;color:var(--text);line-height:1.45;}
  .bw-stamp{font-size:var(--ts-xs);color:var(--dim);white-space:nowrap;}
  .bw-stamp.stale{color:var(--status-warn);}
  .bw-counts{display:flex;gap:var(--sp-4);flex-wrap:wrap;margin:var(--sp-4) 0 var(--sp-5);}
  .bw-count{display:flex;flex-direction:column;gap:2px;}
  .bw-count .n{font-family:Sora,sans-serif;font-size:var(--ts-lg);font-weight:600;line-height:1;}
  .bw-count .l{font-size:var(--ts-xs);color:var(--dim);text-transform:uppercase;letter-spacing:.08em;}
  .bw-warn{border:1px solid rgba(251,191,36,.3);background:rgba(251,191,36,.06);
    border-radius:10px;padding:var(--sp-3) var(--sp-4);margin-bottom:var(--sp-4);font-size:var(--ts-sm);color:var(--text);}
  .bw-warn b{color:var(--status-warn);}
  .bw-warn ul{margin:var(--sp-2) 0 0;padding-left:18px;color:var(--muted);}
  /* The stale-source "check" link had no rule, so it fell back to the UA's #0000ee — 1.6:1 on this
     panel, effectively invisible. Same treatment as the chat citations. */
  .bw-warn a{color:var(--w);display:inline-block;min-height:24px;line-height:24px;vertical-align:top;}
  .bw-item{padding:var(--sp-3) 0;border-bottom:1px solid var(--border);}
  .bw-item:last-child{border-bottom:0;}
  /* NOT .ti — the dashboard already defines .ti as a 17px circular status badge,
     which crushed every headline into one word per line. Namespace everything. */
  /* A block-level headline link is a standalone target, not an inline one — line-height alone left
     it 20px tall, so pad it to the 24px AA floor without changing the type. */
  .bw-item a.bw-ti{display:block;color:var(--text);text-decoration:none;font-size:var(--ts-base);font-weight:500;line-height:1.45;
    padding:2px 0;min-height:24px;box-sizing:border-box;}
  .bw-item a.bw-ti:hover{color:var(--w);text-decoration:underline;}
  .bw-why{font-size:var(--ts-sm);color:var(--muted);margin-top:var(--sp-1);line-height:1.5;}
  .bw-meta{display:flex;align-items:center;gap:var(--sp-2);margin-top:var(--sp-2);flex-wrap:wrap;}
  /* --dim on this lifted chip surface measures 4.21:1 — under AA for the 10px it renders at. */
  .bw-tag{font-size:var(--ts-xs);color:var(--muted);background:rgba(255,255,255,.05);border-radius:5px;padding:1px 7px;}
  .bw-rel{font-family:Sora,sans-serif;font-size:var(--ts-xs);color:var(--dim);}
  .bw-search{width:100%;background:var(--panel3);border:1px solid var(--border);border-radius:10px;
    padding:10px 13px;color:var(--text);font-size:var(--ts-base);font-family:inherit;outline:none;}
  .bw-search:focus{border-color:var(--border-hi);}
  .bw-filters{display:flex;gap:var(--sp-2);margin:var(--sp-3) 0;flex-wrap:wrap;}
  .bw-chip{font-size:var(--ts-xs);padding:4px 11px;border-radius:999px;cursor:pointer;
    border:1px solid var(--border);color:var(--muted);background:transparent;font-family:inherit;}
  .bw-chip:hover{color:var(--text);}
  .bw-chip.on{background:rgba(110,140,255,.14);border-color:var(--border-hi);color:var(--text);}
  .bw-empty{color:var(--dim);font-size:var(--ts-sm);padding:var(--sp-5) 0;text-align:center;}
  .bw-chat{display:flex;flex-direction:column;gap:var(--sp-3);}
  .bw-log{max-height:380px;overflow-y:auto;display:flex;flex-direction:column;gap:var(--sp-3);}
  .bw-msg{font-size:var(--ts-base);line-height:1.6;}
  .bw-msg.u{color:var(--text);background:rgba(110,140,255,.08);border-radius:10px;padding:9px 13px;align-self:flex-end;max-width:85%;}
  .bw-msg.a{color:var(--muted);}
  .bw-msg.a b{color:var(--text);}
  .bw-msg .cite{display:block;font-size:var(--ts-xs);color:var(--dim);margin-top:var(--sp-2);}
  .bw-msg .cite a{color:var(--w);text-decoration:none;}
  .bw-ask{display:flex;gap:var(--sp-2);}
  .bw-send{background:rgba(110,140,255,.16);border:1px solid var(--border-hi);color:var(--text);
    border-radius:10px;padding:0 var(--sp-4);cursor:pointer;font-family:inherit;font-size:var(--ts-sm);}
  .bw-send:disabled{opacity:.45;cursor:not-allowed;}
  .bw-disabled{border:1px dashed var(--border);border-radius:10px;padding:var(--sp-4);
    color:var(--dim);font-size:var(--ts-sm);line-height:1.6;}
  `;
  document.head.appendChild(style);

  const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  // Every title, summary and URL here comes from a third-party feed we do not control,
  // so it is untrusted input rendered into innerHTML. esc() covers text and blocks
  // attribute breakout, but escaping alone does NOT stop a hostile scheme: a feed
  // serving <link>javascript:…</link> would otherwise become a clickable script
  // execution. Allow only http(s), and fail closed to '#'.
  function safeUrl(raw) {
    const value = String(raw == null ? '' : raw).trim();
    if (!value) return '#';
    try {
      const parsed = new URL(value, document.baseURI);
      return (parsed.protocol === 'http:' || parsed.protocol === 'https:') ? parsed.href : '#';
    } catch (err) {
      return '#';
    }
  }

  function daysSince(iso) {
    if (!iso) return null;
    return Math.floor((Date.now() - new Date(iso).getTime()) / 86400000);
  }

  function relDate(iso) {
    const d = daysSince(iso);
    if (d === null) return '';
    if (d <= 0) return 'today';
    if (d === 1) return 'yesterday';
    if (d < 7) return d + 'd ago';
    if (d < 60) return Math.floor(d / 7) + 'w ago';
    return new Date(iso).toISOString().slice(0, 10);
  }

  function sourceName(key) {
    const bw = window.DASHBOARD_BIMWATCH;
    const hit = (bw && bw.sources || []).find((s) => s.key === key);
    return hit ? hit.name : key;
  }

  function itemRow(item) {
    const tags = (item.tags || item.topics || []).map((t) => `<span class="bw-tag">${esc(t)}</span>`).join('');
    const rel = item.rel != null ? item.rel : item.relevance;
    const why = item.why ? `<div class="bw-why">${esc(item.why)}</div>` : '';
    return `<div class="bw-item">
      <a class="bw-ti" href="${esc(safeUrl(item.u || item.url))}" target="_blank" rel="noopener noreferrer">${esc(item.t || item.title)}</a>
      ${why}
      <div class="bw-meta">
        <span class="bw-tag">${esc(sourceName(item.s || item.source))}</span>
        ${tags}
        <span class="bw-rel">${esc(relDate(item.d || item.published))}${rel ? ' · ' + rel : ''}</span>
      </div>
    </div>`;
  }

  function section(title, items, emptyNote) {
    if (!items || !items.length) {
      return `<div class="sec-hd"><span class="t">${esc(title)}</span><span class="ln"></span></div>
        <div class="bw-empty">${esc(emptyNote)}</div>`;
    }
    return `<div class="sec-hd"><span class="t">${esc(title)}</span><span class="ln"></span></div>
      <div>${items.map(itemRow).join('')}</div>`;
  }

  function staleWarning(bw) {
    const stale = bw.stale_sources || [];
    if (!stale.length) return '';
    const rows = stale.map((s) =>
      `<li>${esc(s.name)} — ${esc(s.reason)}${s.home ? ` <a href="${esc(safeUrl(s.home))}" target="_blank" rel="noopener noreferrer">check</a>` : ''}</li>`
    ).join('');
    return `<div class="bw-warn">
      <b>${stale.length} source${stale.length > 1 ? 's have' : ' has'} gone quiet.</b>
      A dead feed looks exactly like a slow news week, so it is flagged rather than assumed.
      <ul>${rows}</ul></div>`;
  }

  function classificationWarning(bw) {
    const b = bw.briefing || {};
    if (b.classification_available !== false) return '';
    return `<div class="bw-warn"><b>Triage did not run.</b>
      Items below are archived and searchable but unranked — ANTHROPIC_API_KEY is not
      configured for the collector, so nothing has been scored yet. See bimwatch/SETUP.md.</div>`;
  }

  function briefingTab(bw) {
    const b = bw.briefing || {};
    const c = b.counts || {};
    const age = daysSince(bw.generated_at);
    const staleStamp = age !== null && age > 2 ? ' stale' : '';

    const counts = [
      ['alert', c.alert || 0], ['learn', c.learn || 0],
      ['fyi', c.fyi || 0], ['noise', c.noise || 0]
    ].map(([k, n]) =>
      `<div class="bw-count"><span class="n" style="color:${TIERS[k].color}">${n}</span>
       <span class="l">${esc(TIERS[k].label)}</span></div>`
    ).join('');

    return `
      <div class="bw-head">
        <div class="bw-headline">${esc(b.headline || 'No briefing yet.')}</div>
        <div class="bw-stamp${staleStamp}">updated ${esc(relDate(bw.generated_at))} · ${bw.archive_count || 0} archived</div>
      </div>
      <div class="bw-counts">${counts}</div>
      ${classificationWarning(bw)}
      ${staleWarning(bw)}
      ${section('Needs attention', b.alerts, 'Nothing this week touches your work directly.')}
      ${section('Worth learning', b.learning, 'No study material surfaced this week.')}
      ${section('Context', b.fyi, 'Nothing else worth noting.')}
    `;
  }

  // ── Search ────────────────────────────────────────────────────────────────
  const state = { query: '', tier: 'all', archive: null, loading: false };

  function matches(item, query, tier) {
    if (tier !== 'all' && (item.tier || 'unsorted') !== tier) return false;
    if (!query) return true;
    const hay = `${item.t || ''} ${item.x || ''} ${item.why || ''} ${(item.tags || []).join(' ')} ${item.s || ''}`.toLowerCase();
    return query.toLowerCase().split(/\s+/).filter(Boolean).every((term) => hay.includes(term));
  }

  function searchTab(bw) {
    const pool = state.archive || bw.recent || [];
    const hits = pool.filter((i) => matches(i, state.query, state.tier));
    const chips = ['all', 'alert', 'learn', 'fyi', 'noise', 'unsorted'].map((t) =>
      `<button class="bw-chip${state.tier === t ? ' on' : ''}" data-bw-tier="${t}">${t === 'all' ? 'All' : esc(TIERS[t].label)}</button>`
    ).join('');

    const deep = state.archive
      ? `<span class="bw-rel">searching all ${pool.length}</span>`
      : (bw.archive_count > pool.length
        ? `<button class="bw-chip" data-bw-deep="1">Search all ${bw.archive_count} →</button>`
        : '');

    return `
      <input class="bw-search" id="bw-q" placeholder="Search titles, summaries, topics…" value="${esc(state.query)}" autocomplete="off">
      <div class="bw-filters">${chips}${deep}</div>
      <div class="bw-rel" style="margin-bottom:var(--sp-3)">${hits.length} result${hits.length === 1 ? '' : 's'}${state.loading ? ' · loading archive…' : ''}</div>
      ${hits.length ? hits.slice(0, 120).map(itemRow).join('') : '<div class="bw-empty">No matches.</div>'}
    `;
  }

  async function loadArchive(bw) {
    if (state.archive || state.loading) return;
    state.loading = true;
    render();
    try {
      const res = await fetch(bw.archive_url || 'bimwatch-archive.json', { cache: 'no-cache' });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      const data = await res.json();
      state.archive = data.items || [];
    } catch (err) {
      state.archiveError = String(err.message || err);
    } finally {
      state.loading = false;
      render();
    }
  }

  // ── Chat ──────────────────────────────────────────────────────────────────
  const chat = { log: [], busy: false, available: null };

  function chatTab() {
    if (chat.available === false) {
      return `<div class="bw-disabled">
        <b>Chat is not available on this URL.</b><br>
        The conversational view runs on a Cloudflare Pages Function, which GitHub Pages
        cannot execute. Everything else on this page works here — open the Cloudflare
        deployment to ask questions.</div>`;
    }
    const log = chat.log.map((m) => {
      if (m.role === 'user') return `<div class="bw-msg u">${esc(m.text)}</div>`;
      const cites = (m.sources || []).map((s) =>
        `<a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`
      ).join(' · ');
      return `<div class="bw-msg a">${esc(m.text).replace(/\n/g, '<br>')}${cites ? `<span class="cite">${cites}</span>` : ''}</div>`;
    }).join('');

    return `<div class="bw-chat">
      <div class="bw-log" id="bw-log">${log || '<div class="bw-empty">Ask about anything in the archive — “what changed in the Revit API this year?”, “should I care about Forma?”, “when did Autodesk announce X?”</div>'}</div>
      <div class="bw-ask">
        <input class="bw-search" id="bw-ask" placeholder="Ask about your BIM feed…" autocomplete="off" ${chat.busy ? 'disabled' : ''}>
        <button class="bw-send" id="bw-send" ${chat.busy ? 'disabled' : ''}>${chat.busy ? '…' : 'Ask'}</button>
      </div>
    </div>`;
  }

  async function sendChat(text) {
    if (!text.trim() || chat.busy) return;
    chat.log.push({ role: 'user', text: text.trim() });
    chat.busy = true;
    render();

    try {
      const res = await fetch('/api/bimwatch-chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          question: text.trim(),
          history: chat.log.slice(-6).map((m) => ({ role: m.role, text: m.text }))
        })
      });
      if (res.status === 404) { chat.available = false; return; }
      if (!res.ok) throw new Error((await res.text()).slice(0, 200) || ('HTTP ' + res.status));
      const data = await res.json();
      chat.log.push({ role: 'assistant', text: data.answer || '(no answer)', sources: data.sources || [] });
    } catch (err) {
      chat.log.push({ role: 'assistant', text: 'Could not reach the chat endpoint: ' + (err.message || err) });
    } finally {
      chat.busy = false;
      render();
      const log = document.getElementById('bw-log');
      if (log) log.scrollTop = log.scrollHeight;
    }
  }

  // ── Shell ─────────────────────────────────────────────────────────────────
  let tab = 'briefing';

  function render() {
    const host = document.getElementById('bw-body');
    if (!host) return;
    const bw = window.DASHBOARD_BIMWATCH;
    host.innerHTML = tab === 'briefing' ? briefingTab(bw)
      : tab === 'search' ? searchTab(bw)
        : chatTab();
    wire();
  }

  function wire() {
    const bw = window.DASHBOARD_BIMWATCH;

    document.querySelectorAll('[data-bw-tab]').forEach((el) => {
      el.onclick = () => { tab = el.dataset.bwTab; render(); };
    });
    document.querySelectorAll('[data-bw-tier]').forEach((el) => {
      el.onclick = () => { state.tier = el.dataset.bwTier; render(); };
    });
    const deep = document.querySelector('[data-bw-deep]');
    if (deep) deep.onclick = () => loadArchive(bw);

    const q = document.getElementById('bw-q');
    if (q) {
      q.oninput = (e) => {
        state.query = e.target.value;
        const pos = e.target.selectionStart;
        render();
        const again = document.getElementById('bw-q');
        if (again) { again.focus(); again.setSelectionRange(pos, pos); }
      };
    }

    const ask = document.getElementById('bw-ask');
    const send = document.getElementById('bw-send');
    if (send && ask) {
      send.onclick = () => { const v = ask.value; ask.value = ''; sendChat(v); };
      ask.onkeydown = (e) => {
        if (e.key === 'Enter') { const v = ask.value; ask.value = ''; sendChat(v); }
      };
      if (!chat.busy) ask.focus();
    }
  }

  // Exposed for index.html's show() branch.
  window.bimwatchView = function bimwatchView() {
    const bw = window.DASHBOARD_BIMWATCH;
    if (!bw) {
      return `<div class="state-unavail">BIM-Watch has no data yet — run
        <code>python -m bimwatch.run</code> to generate bimwatch.js.</div>`;
    }
    const tabs = [['briefing', 'Briefing'], ['search', 'Archive'], ['chat', 'Ask']]
      .map(([k, label]) => `<button class="bw-chip${tab === k ? ' on' : ''}" data-bw-tab="${k}">${label}</button>`)
      .join('');

    setTimeout(render, 0); // populate after index.html injects this HTML
    return `<div class="card" style="padding:var(--sp-5)">
      <div class="bw-filters" style="margin-top:0">${tabs}</div>
      <div id="bw-body"></div>
    </div>`;
  };
})();
