// F:\AI-Dev project dashboard data (schema v4 - tasks added to phases)
// Regenerated by Claude (scheduled daily + on-demand "refresh dashboard").
window.DASHBOARD_DATA = {
  generated: "2026-06-11",
  generatedBy: "scheduled refresh",
  activitySince: "2026-05-29",
  projects: [
    {
      id: "bimpossible",
      name: "BIMpossible Platform",
      icon: "layers",
      oneLiner: "Discipline-neutral BIM data platform above Autodesk's tools (reads ACC, custom interface, write-back later).",
      status: "active",
      phase: "06-11 audit remediation closed: all 06-10 findings fixed + committed (CORE-1/2/3, LIB-13, SCHED-1/2/3, ASST-1/3, lows sweep). CORE-1 + SCHED-2 live-smoked PASS. Waves 10/11/12/13/14/17 live smokes PASSED (11 render modes, real data rows). Wave FE-5 (schedule registry refactor) BuildSpec created. Wave 20 (EntityContextViews) BuildSpec created. Dependabot #35/#36/#59 merged.",
      focus: "Wave 5 XLSX scope-lock: read Wave5_XLSX_PriorArt.md, lock scope → BuildSpec → build",
      progress: { label: "Program phases", phases: [
        { name: "P0-2 Foundation", pct: 100,
          tasks: [
            { label: "Core auth + user model", status: "done" },
            { label: "Database schema + migrations", status: "done" },
            { label: "API gateway + routing", status: "done" },
            { label: "Revit data bridge (ACC read)", status: "done" },
            { label: "Docker/compose dev setup", status: "done" }
          ]
        },
        { name: "P3 Data core", pct: 90, note: "3.9 architecture tail open",
          tasks: [
            { label: "Electrical schedules - 7 Tier-1 shipped", status: "done", note: "All 7 deployed 06-05" },
            { label: "Schedule quick-access bar (auto-width, drag-resize, persist)", status: "done", note: "06-07" },
            { label: "Federated viewer Wave 1", status: "done", note: "06-05" },
            { label: "3.9 architecture tail", status: "active", note: "Remaining open item; not blocking current work" }
          ]
        },
        { name: "P4 Assistant", pct: 85, note: "B2 hardening + audit remediation closed; schedule-push outline only",
          tasks: [
            { label: "B2 rate-limit hardening", status: "done" },
            { label: "B2 byte-cap + deadline handling", status: "done" },
            { label: "B2 write-allowlist + injection guard", status: "done" },
            { label: "Assistant markdown + pill chrome", status: "done", note: "06-07" },
            { label: "Wave 4.8 close-out: D1-D7 ratification", status: "done", note: "Ratified 06-10; D2 Voltage/Mains refuted as a gate" },
            { label: "Wave 4.8: Tier-2 disposition (D3 rec: defer to 4.8.x)", status: "done", note: "D3: deferred to 4.8.x" },
            { label: "Wave 4.8 close-out doc", status: "done", note: "2026-06-10__wave-4-8-closeout.md" },
            { label: "Schedule-push: staleness cadence, classifier rules, SPF ship location", status: "pending" }
          ]
        },
        { name: "P5 Surfaces / Viewer", pct: 50, note: "federated-viewer smoke discharged + CSP hardened; XLSX + FE-5 registry refactor open",
          tasks: [
            { label: "Federated-viewer Wave 1 smoke (GA-H12)", status: "done" },
            { label: "CSP hardened - viewer fonts 55→0 violations", status: "done", note: "PR #79 06-10" },
            { label: "Wave 5 XLSX scope-lock", status: "active", note: "Prior-art done 06-02; scope-lock next" },
            { label: "Wave FE-5 schedule registry refactor", status: "active", note: "BuildSpec created 06-11; 19-arm ternary + 19 hook calls in page.tsx" },
            { label: "Viewer-wave package scoping", status: "pending", note: "Ownership question logged 06-04" },
            { label: "Further viewer waves", status: "pending" }
          ]
        },
        { name: "Waves 10-19 Rollout", pct: 35, note: "Waves 10/11/12/13/14/17 shipped + live-smoked (11 render modes). Windows shaper not built. Waves 15/16/18/19 not started.",
          tasks: [
            { label: "Wave specs drafted", status: "done" },
            { label: "Waves 10/11/12/13/14/17 discipline-schedule shapers + live smokes", status: "done", note: "11 render modes confirmed with real data rows 06-11" },
            { label: "Wave 10 Windows schedule (shaper not built)", status: "active", note: "Bar placeholder only; OST_Windows probe needed" },
            { label: "Remaining discipline waves (15/16/18/19)", status: "pending" }
          ]
        }
      ]},
      activity: [11,37,15,44,44,36,45,48,16,13,0,51,121,6],
      lastActivity: { date: "2026-06-11", summary: "Audit remediation closed: CORE-1/2/3 chokepoint, LIB-13 strict-numeric, SCHED-1/2/3 varies-aggregation/MCA-tags, ASST-1/3 explore-allowlist, lows sweep; CORE-1+SCHED-2 live-smoked PASS; 3 Dependabot bumps merged (#35/#36/#59)" },
      branch: "main synced to origin (0 ahead); Dependabot PRs #17/#18 (react major) still open",
      git: { warn: "~7 local fix/perp-audit-* branches may still sit ahead of origin/main (content merged via PR but local branches unretired). main 0 ahead of origin. Also un-retired: feat/schedules-bar-header, feat/electrical-schedules-bar (merged, superseded)." },
      nextActions: [
        "Wave 5 XLSX scope-lock: read Wave5_XLSX_PriorArt.md, lock scope → BuildSpec → build",
        "Wave FE-5 schedule registry refactor: BuildSpec ready (06-11); scope-lock → build",
        "Wave 10 Windows schedule: shaper not built (bar placeholder only) — probe OST_Windows → full shaper→endpoint→whitelist→TS→view→bar stack",
        "Dependabot PRs: review #36 typescript-eslint 7→8 breaking changes, then #17/#18 react major (check compat before merging)",
        "Owed smokes (ledger): logout-clears-both-cookies, P1-F same-version republish (Revit touch), assistant 429, cold-Circuits preparing->rows",
        "Wave 6 (backend pytest + thin permissions) — unlocks Phase 4b action-enabled assistant",
        "Retire leftover local audit branches + 2 stale schedules-bar branches"
      ],
      pendingDecisions: [
        "Schedule-push: staleness cadence, classifier rules, fidelity degradation list, SPF ship location",
        "Viewer-wave package scoping (ownership question logged 06-04)"
      ],
      blockers: [],
      reminders: [
        "All 06-10 audit findings fixed + committed 06-11; CORE-1+SCHED-2 live-smoked PASS; next formal audit Mon 06-16 will re-verify",
        "Codebase graph stale — graph-metrics.js empty; push or run a wave to refresh",
        "Wave 20 (EntityContextViews) BuildSpec created 06-11 — not yet in WAVE-STATUS.md ledger; add row when ready to track",
        "Drop _saved_views_snapshot_2026_05_24 after 2026-06-23",
        "Security carryovers still open: X2 limit=0, S9 APS raw errors, X11 filename sanitization — verify before multi-user deploy",
        "5 open Dependabot PRs (#17 react, #18 react-dom, #35 happy-dom, #36 typescript-eslint, #59 backend Python) — batch with care; #36 + #17/#18 have breaking-change risk"
      ],
      links: [
        { label: "STATE doc (canonical, 06-10)", path: "F:\\AI-Dev\\BIMpossible_Workspace\\00_Strategy\\BIMpossible_STATE_2026-06-10.md" },
        { label: "Audit remediation 8-PR wave (06-10)", path: "F:\\AI-Dev\\BIMpossible_Workspace\\01_BuildLog\\2026-06-10__audit-remediation-eight-pr-wave.md" },
        { label: "Waves 10-17 discipline schedules close-out (06-10)", path: "F:\\AI-Dev\\BIMpossible_Workspace\\01_BuildLog\\2026-06-10__discipline-schedules-waves-10-17-closeout.md" },
        { label: "Wave FE-5 BuildSpec (06-11)", path: "F:\\AI-Dev\\BIMpossible_Workspace\\00_Strategy\\BIMpossible_Wave-FE5_ScheduleRegistry_BuildSpec.md" },
        { label: "Build log", path: "F:\\AI-Dev\\BIMpossible_Workspace\\01_BuildLog" },
        { label: "Code", path: "F:\\AI-Dev\\BIMpossible" }
      ],
      recent: [
        "2026-06-11 - audit remediation closed: CORE-1/2/3 chokepoint+prewarm race, LIB-13 strict-numeric, SCHED-1/2/3 varies-agg+MCA-tags, ASST-1/3 explore-allowlist, lows sweep (SPINE/FEA/SCHED/CORE-4/ASST-2); CORE-1+SCHED-2 live-smoked PASS; 3 Dependabot bumps; Wave FE-5 + Wave 20 BuildSpecs created",
        "2026-06-10 - Waves 10-17 discipline schedules close-out: 11 render modes live-smoked PASS (real data rows confirmed). Wave 4.8 CLOSED. New 06-10 full audit (7 agents): 1H+7M+15L+3I found (all since fixed)",
        "2026-06-10 - audit-remediation eight-PR wave (B1-B6 viewer-token/refresh-lock/assistant-hardening/od2/auth-hygiene/phase-sum + GA retention-nonblocking); CSP viewer fonts 55→0 (#79), drag perf (#84), a11y (#85), honest README (#86)",
        "2026-06-09 - perf fixes wave 4.6.5 + full-project audit (GA-C1)",
        "2026-06-07 - schedules quick-access bar merged (auto-width, drag-resize+persist, theme pills); assistant markdown + pill chrome",
        "2026-06-05 - ALL 7 Tier-1 electrical schedules shipped; federated viewer Wave 1 (#46); assistant help library"
      ],
      audit: {
        lastRun: "2026-06-10",
        runType: "Full top-to-bottom (7 adversarial review agents)",
        cadence: "weekly Mon 6am + on-demand",
        counts: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
        closedLastRun: 64,
        trend: "improving",
        reportPath: "F:\\AI-Dev\\BIMpossible_Workspace\\02_Reference\\Audit Reports\\2026-06-10__audit-report-full.md",
        ledgerPath: "F:\\AI-Dev\\BIMpossible_Workspace\\02_Reference\\_audit-runs.md",
        open: []
      },
      waves: {
        updated: "2026-06-10",
        source: "F:\\AI-Dev\\BIMpossible_Workspace\\00_Strategy\\BIMpossible_WAVE-STATUS.md",
        summary: { done: 12, built: 6, inFlight: 1, ahead: 9 },
        current: [
          { id: "1", title: "Foundation consolidation", status: "PARTIAL", note: "Open: audit-branch merge, live-DB Phase 3.5 migration, Alembic baseline (HIGH-8)" },
          { id: "10-14,17", title: "Discipline schedule shapers (Arch/Mech/Plumb/Struct/FP/ICT-LV)", status: "BUILT", date: "2026-06-10", note: "All 11 render modes live-smoked PASS 06-11; Windows shaper still missing in Wave 10" },
          { id: "5", title: "Phase 3.7 minimal XLSX export", status: "SCOPE-LOCK", note: "prior-art done 06-02; scope-lock next" },
          { id: "FE-5", title: "Schedule registry refactor (page.tsx 19-arm ternary)", status: "PLANNED", note: "BuildSpec created 06-11; deferred from 06-10 low sweep" }
        ],
        lastCompleted: { id: "4.8", title: "Electrical schedule completeness", date: "2026-06-10" },
        drift: [ "No wave-*-complete git tags exist - Complete-Wave.ps1 tagging isn't in use, so the ledger is the sole completion signal (FYI, not an error)" ]
      }
    },
    {
      id: "addins",
      name: "Add-Ins / RevitLink",
      icon: "wrench",
      oneLiner: "Revit ribbon add-ins: BIMpossible.RevitLink (9/13 shipped + 8 BIM manager tools built) + Trade QA Scanner suite (6 trades deployed).",
      status: "active",
      phase: "Major expansion 06-10/11: Tools 10-13 shipped (Fix Title Blocks, Retag Rooms, Push View Templates, Trim Sheets) → RevitLink 9/13 live. Tools 14-21 built via TDD (Warning Scanner, In-Place Families, Workset Audit, Element ID Finder, Batch Rename Views, VT Audit, Scope Box Manager, Batch PDF Export). ElectricalParamSyncWindow improved. feat/model-health-report retired; all pushed to main.",
      focus: "Tool 7 Phase 1 smoke test in Revit; then Definition of Done sweep (icons/guides/tooltips) for Tools 10-21",
      progress: { label: "Tracks", phases: [
        { name: "RevitLink tools (9/13 shipped)", pct: 72,
          tasks: [
            { label: "Tools 1–6 shipped", status: "done" },
            { label: "Tool 7 (Build Sheet Set from Arch Link)", status: "active", note: "Phase 1 built; smoke test owed in Revit" },
            { label: "Tools 8–9", status: "pending", note: "IDEA stage" },
            { label: "Tools 10–13 shipped", status: "done", note: "06-10: Fix Title Blocks, Retag Rooms, Push View Templates, Trim Sheets" }
          ]
        },
        { name: "BIM Manager Tools (14-21 built)", pct: 40, note: "TDD green; not yet in SHIP state; Definition of Done owed",
          tasks: [
            { label: "Tool 14 Warning Scanner", status: "done", note: "WarningScannerCommand + 6 tests" },
            { label: "Tool 15 In-Place Family Finder", status: "done", note: "TDD green" },
            { label: "Tool 16 Workset Audit", status: "done", note: "WorksetAuditEntry + 5 tests" },
            { label: "Tool 17 Element ID Finder", status: "done", note: "WPF dialog + clipboard copy" },
            { label: "Tool 18 Batch Rename Views", status: "done", note: "ViewRenameRule + 7 tests" },
            { label: "Tool 19 View Template Audit", status: "done", note: "HTML+CSV report, TDD green" },
            { label: "Tool 20 Scope Box Manager", status: "done", note: "TDD green" },
            { label: "Tool 21 Batch PDF Export", status: "done", note: "SheetExportSpec + PdfExportGrouper + 4 tests" },
            { label: "Definition of Done (icons, guides, tooltips) for 14-21", status: "pending" },
            { label: "TOOL_BACKLOG.md numbered table updated with 14-21", status: "pending" }
          ]
        },
        { name: "Tool 7 sheet set", pct: 60, note: "Phase 1 built; smoke owed",
          tasks: [
            { label: "Phase 1 (sheets) — built", status: "done" },
            { label: "Phase 1 smoke test in Revit", status: "active", note: "Next action — run it" },
            { label: "Phase 2 (view placement)", status: "pending" }
          ]
        },
        { name: "QA scanners (6/7 deployed)", pct: 72, note: "Core consolidated + audit-hardened; live smokes owed",
          tasks: [
            { label: "6 trades deployed", status: "done" },
            { label: "ModelQA.Core consolidated (816 tests green)", status: "done", note: "06-10 — 17 files × ~100 copies → one netstandard2.0 lib" },
            { label: "Audit-hardened pass", status: "done", note: "06-09 — CSV injection guard x7, culture-invariant, rolling log" },
            { label: "Architectural live smoke (4 tools, 21 tests)", status: "active" },
            { label: "E / M / P / FP / S live spikes", status: "pending" },
            { label: "Civil scanner (Trade 7)", status: "pending", note: "Scope decision parked — unanswered" }
          ]
        }
      ]},
      activity: [0,0,0,0,22,24,38,11,0,1,0,8,57,3],
      lastActivity: { date: "2026-06-11", summary: "Tools 14-21 built + ribbon-wired (8 BIM manager tools via TDD); ReportHelper shared component; deferred tool ideas documented" },
      branch: "main",
      git: { warn: "BIMpossible.RevitLink still has NO git repo (git init pending). feat/model-health-report retired (merged). main 0 ahead of origin/main." },
      nextActions: [
        "Tool 7 Phase 1 (sheets) smoke test; Phase 2 = view placement",
        "Definition of Done sweep: icons + How-To guides + tooltip/F1 wiring for Tools 10-21",
        "QA Scanners: live smoke Architectural (4 tools, 21 tests); live spikes for E/M/P/FP/S collectors",
        "git init BIMpossible.RevitLink",
        "Update TOOL_BACKLOG.md: add Tools 14-21 to numbered backlog table with status"
      ],
      pendingDecisions: [ "Civil Shared-Coordinate Audit scanner - scope unanswered (PARKED)" ],
      blockers: [],
      reminders: [
        "Core.dll co-loads in one Revit process: redeploy ALL add-ins together when Core changes",
        "Tools 14-21 committed to main but not yet in TOOL_BACKLOG.md numbered table — update table + assign status",
        "Definition of Done (icons, guides, tooltips) owed for all recently shipped/built tools (10-21)",
        "Deferred: Deploy-Local.ps1 PS 5.1-safe; Revit dev-mode hot-reload"
      ],
      links: [
        { label: "Tool backlog", path: "F:\\AI-Dev\\Add-Ins\\TOOL_BACKLOG.md" },
        { label: "ModelQA consolidation decision (06-10)", path: "F:\\AI-Dev\\Add-Ins\\decision-log\\2026-06-10__modelqa-consolidation.md" },
        { label: "Audit fix pass (06-09)", path: "F:\\AI-Dev\\Add-Ins\\decision-log\\2026-06-09__audit-fix-pass.md" },
        { label: "Dev notes", path: "F:\\AI-Dev\\Add-Ins\\BIMpossible.RevitLink\\DEV-NOTES.md" }
      ],
      recent: [
        "2026-06-11 - Tools 14-21 built + ribbon-wired (Warning Scanner, In-Place Families, Workset Audit, Element ID Finder, Batch Rename Views, VT Audit, Scope Box Manager, Batch PDF Export); ReportHelper shared; deferred tool ideas doc",
        "2026-06-10 - Tools 10-13 shipped (Fix Title Blocks, Retag Rooms, Push View Templates, Trim Sheets); ElectricalParamSyncWindow filter bar + auto-collapse + collapse memory; Electrical ribbon additions (Equip/One-Line sync, Link Symbols); feat/model-health-report retired",
        "2026-06-10 - ModelQA.Core consolidation: 17 files x ~100 copies -> one shared netstandard2.0 lib; 816 tests green",
        "2026-06-09 - audit fix pass: pipe B-Off enacted, culture-invariant, CSV injection guard x7, rolling log, dead-planner removal"
      ],
      audit: {
        lastRun: "2026-06-09",
        runType: "google / perp / perf (on-demand)",
        cadence: "on-demand",
        counts: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
        closedLastRun: 9,
        trend: "improving",
        reportPath: "F:\\AI-Dev\\Add-Ins\\audits\\2026-06-09__perp-audit.md",
        open: []
      }
    },
    {
      id: "site",
      name: "BIMpossible Site",
      icon: "globe",
      oneLiner: "bimpossible.com marketing/portfolio site (B-grade at M3, SaaS marketing C-grade by M6). Astro + Tailwind planned.",
      status: "active",
      phase: "M0 build hardened: Astro site built, three audits (perf/architecture/code-review) run + cleared 06-09, deploy infra added 06-10 (Cloudflare functions, Lighthouse CI, tests). Not yet deployed - gated on IP lockdown",
      focus: "IP-Lockdown-Checklist Phase 1 (domain/registrar/handles/LLC) - M0 deploy is still blocked on it",
      progress: { label: "Milestones", phases: [
        { name: "Strategy & roadmaps", pct: 100,
          tasks: [
            { label: "Roadmap index created", status: "done" },
            { label: "Astro + Tailwind stack locked", status: "done" }
          ]
        },
        { name: "IP lockdown", pct: 20, note: "7 of 34 items checked",
          tasks: [
            { label: "7 / 34 checklist items done", status: "done" },
            { label: "Domain registration", status: "active" },
            { label: "Registrar + handles", status: "pending" },
            { label: "LLC formation", status: "pending" },
            { label: "Remaining 27 checklist items", status: "pending" }
          ]
        },
        { name: "M0 deploy target", pct: 55, note: "built + audited + hardened + deploy infra in; not live, gated on IP lockdown",
          tasks: [
            { label: "Astro site scaffold (6 pages + global.css)", status: "done", note: "06-04" },
            { label: "Perf audit cleared", status: "done", note: "06-09 — fonts subset 71→13KB, lazy logos" },
            { label: "Architecture audit cleared", status: "done", note: "06-09 — dead deps removed" },
            { label: "Code-review audit cleared", status: "done", note: "06-09 — contact hardening" },
            { label: "Cloudflare functions + Lighthouse CI + tests + scripts", status: "done", note: "06-10" },
            { label: "Live deploy", status: "blocked", note: "Gated on IP lockdown Phase 1 completing" }
          ]
        },
        { name: "M3 portfolio site", pct: 0,
          tasks: [
            { label: "Design + content", status: "pending" },
            { label: "Build", status: "pending" },
            { label: "Deploy", status: "pending" }
          ]
        }
      ]},
      activity: [1,2,1,0,0,0,1,0,0,0,0,5,1,0],
      lastActivity: { date: "2026-06-10", summary: "Deploy infra added: Cloudflare functions/, Lighthouse CI (lighthouserc.json), tests/, scripts/, package-lock regen" },
      branch: null, git: null,
      nextActions: [
        "IP-Lockdown-Checklist Phase 1 (7/34 done) - prerequisite for M0",
        "Deploy M0 once IP lockdown clears - build + audits + infra are ready",
        "PUT-PRODUCT-ONLINE step-by-step - execute when ready"
      ],
      pendingDecisions: [],
      blockers: ["M0 blocked until IP-Lockdown Phase 1 done"],
      reminders: ["Nameplate PNGs (~600KB x2) + Hero.png (7.7MB) still raster - SVG wordmark needs Zeriah's eye"],
      links: [
        { label: "Roadmap index", path: "F:\\AI-Dev\\BIMpossible Site\\00_README.md" },
        { label: "IP lockdown checklist", path: "F:\\AI-Dev\\BIMpossible Site\\IP-Lockdown-Checklist.md" },
        { label: "Build log", path: "F:\\AI-Dev\\BIMpossible Site\\01_BuildLog" }
      ],
      recent: [
        "2026-06-10 - deploy infra (Cloudflare functions, Lighthouse CI, tests, scripts)",
        "2026-06-09 - three audits run (perf / architecture-google / code-review-perp) + H1-H4/M1 highs and M2-M6/L1-L10 cleared (fonts subset 71->13KB, dead deps removed, lazy logos, contact hardening)",
        "2026-06-04 - Astro page scaffold (index/product/about/contact/leaders/bim-managers + global.css)"
      ],
      audit: {
        lastRun: "2026-06-09",
        runType: "perf / architecture / code-review (on-demand)",
        cadence: "on-demand",
        counts: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
        closedLastRun: 20,
        trend: "improving",
        reportPath: "F:\\AI-Dev\\BIMpossible Site\\01_BuildLog\\_site-audit-runs.md",
        open: []
      }
    },
    {
      id: "pickem",
      name: "Preseason Pick'em",
      icon: "trophy",
      oneLiner: "Next.js pick'em app (PreseasonPickem-app). Stack locked, Phase 1 auth started.",
      status: "dormant",
      phase: "Phase 1 auth + scoring/rankings libs added 06-01 (status still flagged dormant pending human call)",
      focus: "Decide: resume before NFL preseason or park explicitly",
      progress: { label: "Build", phases: [
        { name: "P0 Bootstrap + stack", pct: 100,
          tasks: [
            { label: "Next.js + stack setup", status: "done" },
            { label: "Docker compose + scripts", status: "done" }
          ]
        },
        { name: "P1 Auth", pct: 25,
          tasks: [
            { label: "Auth lib scaffolded", status: "done" },
            { label: "User sessions + flows", status: "active", note: "Ref: 03_ChatExports/2026-05-24__phase1-auth.md" }
          ]
        },
        { name: "Picks + scoring MVP", pct: 30, note: "scoring engine/leaderboard + rankings sync libs in (06-01)",
          tasks: [
            { label: "Scoring engine lib", status: "done", note: "06-01" },
            { label: "Leaderboard lib", status: "done", note: "06-01" },
            { label: "Rankings sync (Sleeper / stats)", status: "done", note: "06-01" },
            { label: "Wire libs into app", status: "pending" },
            { label: "Pick submission UI", status: "pending" }
          ]
        },
        { name: "Deploy", pct: 0,
          tasks: [
            { label: "Hosting setup", status: "pending" },
            { label: "Production deploy", status: "pending", note: "Hard deadline: NFL preseason (August)" }
          ]
        }
      ]},
      activity: [0,0,0,1,0,0,0,0,0,0,0,0,0,0],
      lastActivity: { date: "2026-06-01", summary: "rankings (sleeper/stats/sync) + scoring (engine/leaderboard/manual-tiebreak) libs added" },
      branch: null, git: null,
      nextActions: [ "Resume Phase 1 auth per 03_ChatExports/2026-05-24__phase1-auth.md; wire the new scoring/rankings libs into the app" ],
      pendingDecisions: [],
      blockers: [],
      reminders: [
        "Idle since 2026-06-01 (10 days) - confirm dormant status; NFL preseason deadline approaching (August)",
        "Hard real-world deadline: NFL preseason (August)"
      ],
      links: [
        { label: "PRD", path: "F:\\AI-Dev\\Preseason Pick'em\\PRD.md" },
        { label: "Workspace index", path: "F:\\AI-Dev\\Preseason Pick'em\\WORKSPACE_INDEX.md" },
        { label: "App", path: "F:\\AI-Dev\\Preseason Pick'em\\PreseasonPickem-app" }
      ],
      recent: [
        "2026-06-01 - rankings + scoring engine/leaderboard libs added"
      ]
    },
    {
      id: "laundry",
      name: "Laundry Gig",
      icon: "box",
      oneLiner: "Next.js demo app (Lazy Demo) with docker-compose + start/stop scripts.",
      status: "dormant",
      phase: "Unknown - no state doc exists",
      focus: "Capture a status note so this becomes trackable",
      progress: null,
      activity: [0,0,0,1,0,0,1,0,0,0,0,0,0,0],
      lastActivity: { date: "2026-06-04", summary: "CLAUDE-CODE-PROMPT.md added (06-04); app scaffold (package/prisma/scripts) touched 06-01" },
      branch: null, git: null,
      nextActions: [ "Write a status note - dashboard can't track this project until one exists" ],
      pendingDecisions: [],
      blockers: [],
      reminders: ["No state doc - tracking is folder-mtime only"],
      links: [
        { label: "README", path: "F:\\AI-Dev\\Laundry Gig\\README.md" },
        { label: "Docs", path: "F:\\AI-Dev\\Laundry Gig\\docs" }
      ],
      recent: []
    },
    {
      id: "families",
      name: "Families by AI",
      icon: "cube",
      oneLiner: "Revit family audit + standardize tool (Family Fixer). Path A: offline Python auditor. Path B: C# revit-mcp automation. Focus: S&L One-Line electrical symbol families.",
      status: "paused",
      phase: "Git repo scaffolded 06-11 (code-only, no .rfa binaries). Path A (Python auditor) + Path B (C# Revit scripts via revit-mcp). Developmental/One Line Symbols folder updated 06-11 (ties into Add-Ins One-Line sync work).",
      focus: "Run Path A auditor against a real .rfa repo; green-light Path B only after it validates",
      progress: { label: "Two-path plan", phases: [
        { name: "Path A auditor build", pct: 60,
          tasks: [
            { label: "Tool scaffold + README", status: "done", note: "05-28" },
            { label: "Core auditor logic (partial)", status: "active", note: "~60% built; untouched 05-28 to 06-11" }
          ]
        },
        { name: "Path A validation", pct: 0,
          tasks: [
            { label: "Run against a real .rfa repo", status: "pending", note: "Must pass before Path B starts" }
          ]
        },
        { name: "Path B live automation", pct: 0,
          tasks: [
            { label: "revit-mcp integration design", status: "pending", note: "Not started - blocked on Path A validation" },
            { label: "Live automation build", status: "pending" }
          ]
        }
      ]},
      activity: [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      lastActivity: { date: "2026-06-11", summary: "Git repo scaffolded (.gitignore code-only/no-.rfa, .gitattributes, LICENSE, CHANGELOG); Developmental/One Line Symbols folder updated (linked to Add-Ins electrical sync work)" },
      branch: null, git: null,
      nextActions: [ "Run Path A against a real family repo; green-light Path B only after it validates" ],
      pendingDecisions: [],
      blockers: [],
      reminders: [
        "New activity 06-11 (git scaffolding + One Line Symbols) but status remains paused per auto-promote rule",
        "Idle 05-28 to 06-11 on core auditor; auto-demote to dormant at 21 idle days on core auditor (rule 7)"
      ],
      links: [ { label: "Tool README", path: "F:\\AI-Dev\\Families by AI\\README.md" } ],
      recent: [
        "2026-06-11 - git repo scaffolded (code-only, no .rfa binaries); Developmental/One Line Symbols folder updated"
      ]
    }
  ]
};
