// F:\AI-Dev project dashboard data (schema v4 - tasks added to phases)
// Regenerated by Claude (scheduled daily + on-demand "refresh dashboard").
window.DASHBOARD_DATA = {
  generated: "2026-06-12",
  generatedBy: "on-demand refresh",
  activitySince: "2026-05-30",
  projects: [
    {
      id: "bimpossible",
      name: "BIMpossible Platform",
      icon: "layers",
      oneLiner: "Discipline-neutral BIM data platform above Autodesk's tools (reads ACC, custom interface, write-back later).",
      status: "active",
      phase: "116 closed PRs. Waves 5/6/6.5/7/16/20/21 + Phase 6 all shipped 2026-06-12. Critical bugfix: _SCHEDULE_EXTRA_CATEGORIES — arch/structural warm pool was missing, all arch/structural schedule endpoints returned 0 rows (fixed); Windows smoke PASSED. Next.js 14→15.5.19 (CVE-2025-29927 closed). Wave 4.9 Classification Enrichment scoped + BuildSpec ready. Wave 8 (Revit Link multi-user) is the next code wave after prod deploy.",
      focus: "Deploy PR #112 to prod (5 Alembic migrations + env vars + prewarm DB cleanup), then run Wave 4.9 overnight (BuildSpec ready, no prerequisites)",
      progress: { label: "Program phases", phases: [
        { name: "P0-2 Foundation", pct: 100,
          tasks: [
            { label: "Core auth + user model", status: "done" },
            { label: "Database schema + migrations", status: "done" },
            { label: "API gateway + routing", status: "done" },
            { label: "Revit data bridge (ACC read)", status: "done" },
            { label: "Docker/compose dev setup", status: "done" }
          ]
        },
        { name: "P3 Data core", pct: 97, note: "Wave 7 (Phase 3.9 automation) shipped with all 3 live smokes PASSED",
          tasks: [
            { label: "Electrical schedules - 7 Tier-1 shipped", status: "done", note: "All 7 deployed 06-05" },
            { label: "Schedule quick-access bar (auto-width, drag-resize, persist)", status: "done", note: "06-07" },
            { label: "Federated viewer Wave 1", status: "done", note: "06-05" },
            { label: "3.9 architecture tail (Wave 7)", status: "done", note: "06-12 — calc-field 5k gate, share-by-link, stale-cache banner; all 3 smokes PASSED" }
          ]
        },
        { name: "P4 Assistant", pct: 93, note: "Phase 4b HITL action-enabled assistant shipped + smoke PASSED; schedule-push outline only",
          tasks: [
            { label: "B2 rate-limit hardening", status: "done" },
            { label: "B2 byte-cap + deadline handling", status: "done" },
            { label: "B2 write-allowlist + injection guard", status: "done" },
            { label: "Assistant markdown + pill chrome", status: "done", note: "06-07" },
            { label: "Wave 4.8 close-out: D1-D7 ratification", status: "done", note: "Ratified 06-10" },
            { label: "Phase 4b action-enabled assistant (HITL)", status: "done", note: "06-11/12 — HITL approval SSE + /assistant/resume; smoke PASSED" },
            { label: "Schedule-push: staleness cadence, classifier rules, SPF ship location", status: "pending" }
          ]
        },
        { name: "P5 Surfaces / Viewer", pct: 65, note: "Wave 5 XLSX shipped; Wave 4.9 classification enrichment next",
          tasks: [
            { label: "Federated-viewer Wave 1 smoke (GA-H12)", status: "done" },
            { label: "CSP hardened - viewer fonts 55→0 violations", status: "done", note: "PR #79 06-10" },
            { label: "Wave 5 XLSX export", status: "done", note: "06-11 PR #109 — GET /data/elements/xlsx + Sheet button" },
            { label: "Wave 4.9 Classification Enrichment (OmniClass + CSI schedule columns)", status: "active", note: "Scoped 06-12; BuildSpec + pre-written module ready; overnight-runnable" },
            { label: "Viewer-wave package scoping", status: "pending", note: "Ownership question logged 06-04" },
            { label: "Further viewer waves", status: "pending" }
          ]
        },
        { name: "Waves 10-21 Rollout", pct: 50, note: "Waves 10/11/12/13/14/16/17 code shipped (smokes owed). Waves 20/21 shipped. Waves 15/18/19 not started.",
          tasks: [
            { label: "Wave specs drafted", status: "done" },
            { label: "Waves 10/11/12/13/14/17 discipline-schedule shapers", status: "done", note: "Code shipped; live smokes still owed for all 6 waves" },
            { label: "Wave 10 Windows smoke PASSED", status: "done", note: "06-12 — _SCHEDULE_EXTRA_CATEGORIES bugfix enabled; 4 instances confirmed" },
            { label: "Wave 16 Interiors (bar config)", status: "done", note: "Bar config live via PR #112; no dedicated shapers yet; smoke owed" },
            { label: "Wave 20 billing cost view + multi-provider BYO keys", status: "done", note: "PR #116; admin smokes PASSED; BYO-key routing smoke owed" },
            { label: "Wave 21 click-to-sort all schedule tables", status: "done", note: "PR #115; 8 tests green" },
            { label: "Live smokes for Waves 11/12/13/14/17 (MEP + Structural + ICT)", status: "active", note: "Need prod deploy of bugfix first" },
            { label: "Remaining discipline waves (15/18/19)", status: "pending" }
          ]
        },
        { name: "P6 Platform / Billing", pct: 75, note: "Access tiers + billing guardrails shipped; prod deploy pending",
          tasks: [
            { label: "Wave 6 thin permissions (SEC-M4 + identity coverage)", status: "done", note: "PR #110 06-11" },
            { label: "Phase 6 access tiers + billing guardrails", status: "done", note: "PR #112 06-12; client_keys Fernet-encrypted" },
            { label: "Prod deploy (5 Alembic migrations + env vars)", status: "active", note: "PR #112 on main; deploy + alembic upgrade head + prewarm cleanup required" },
            { label: "Wire usage_logger.py into SSE chat path", status: "pending" }
          ]
        }
      ]},
      activity: [37,15,44,44,36,45,48,16,13,0,51,121,6,100],
      lastActivity: { date: "2026-06-12", summary: "Wave 7 shipped (Phase 3.9: calc-field gate, share-by-link, stale-cache banner; all 3 smokes PASSED). Wave 16/20/21 shipped. _SCHEDULE_EXTRA_CATEGORIES critical bugfix. Windows smoke PASSED. Next.js 15.5.19 (CVE-2025-29927 closed)." },
      branch: "main at 59248c3; 0 open PRs; 0 ahead of origin",
      git: { warn: "Local fix/perp-audit-* branches may not be retired yet (content merged via PR). Verify with git branch -r." },
      nextActions: [
        "Deploy PR #112 (already on main): alembic upgrade head (5 migrations), set BIMPOSSIBLE_ADMIN_ENABLED=1 + BIMPOSSIBLE_ADMIN_SECRET, then DELETE stale done-rows in relationship_prewarm_jobs per model (forces warm pool re-fetch with _SCHEDULE_EXTRA_CATEGORIES)",
        "Wave 4.9 overnight run: feed BuildSpec prompt (BIMpossible_Wave49_ClassificationEnrichment_BuildSpec.md) into Claude Code session at F:\\AI-Dev\\BIMpossible\\",
        "Live smokes post-deploy: Waves 11/12/13/14/17 MEP/Structural/ICT schedules (need prod bugfix deploy first)",
        "Wave 20 BYO-key assistant routing smoke (requires live assistant turn with a key configured)",
        "Audit expr-eval 2.0.2: grep -r 'evaluate(' frontend/app — prototype pollution CVE, no upstream fix; sanitize or replace with mathjs",
        "Wave 8 (Revit Link multi-user) — scoping after prod deploy stabilizes"
      ],
      pendingDecisions: [
        "Schedule-push: staleness cadence, classifier rules, fidelity degradation list, SPF ship location",
        "Wave 16 Interiors: build dedicated shapers now or batch with Wave 15 Civil?"
      ],
      blockers: [],
      reminders: [
        "Prod deploy owed: 5 Alembic migrations + 2 env vars (BIMPOSSIBLE_ADMIN_ENABLED, BIMPOSSIBLE_ADMIN_SECRET) + prewarm DB cleanup (delete stale done-jobs per model) — required before live smokes for Waves 11-17",
        "expr-eval 2.0.2: 1 high CVE (prototype pollution via evaluate()) — no upstream fix; audit call sites before multi-user deploy",
        "Wave 4.9 BuildSpec + pre-written Python module ready in workspace (02_Reference/classification_enrichment.py) — no prerequisites, overnight-runnable",
        "WAVE-STATUS.md ledger incomplete — rows for waves 10-21 missing from table; add rows to get accurate summary counts on next refresh",
        "Drop _saved_views_snapshot_2026_05_24 after 2026-06-23",
        "Wave 20 admin UI BYO-key smoke still owed: open /admin → API Keys tab → verify provider dropdown shows anthropic/openai/google/etc"
      ],
      links: [
        { label: "STATE doc (canonical, 06-12)", path: "F:\\AI-Dev\\BIMpossible_Workspace\\00_Strategy\\BIMpossible_STATE_2026-06-12.md" },
        { label: "Wave 4.9 BuildSpec", path: "F:\\AI-Dev\\BIMpossible_Workspace\\00_Strategy\\BIMpossible_Wave49_ClassificationEnrichment_BuildSpec.md" },
        { label: "classification_enrichment.py (pre-written module)", path: "F:\\AI-Dev\\BIMpossible_Workspace\\02_Reference\\classification_enrichment.py" },
        { label: "Wave 4.8 close-out (06-10)", path: "F:\\AI-Dev\\BIMpossible_Workspace\\01_BuildLog\\2026-06-10__wave-4-8-closeout.md" },
        { label: "Build log", path: "F:\\AI-Dev\\BIMpossible_Workspace\\01_BuildLog" },
        { label: "Code", path: "F:\\AI-Dev\\BIMpossible" }
      ],
      recent: [
        "2026-06-12 - Wave 7 (Phase 3.9 automation): calc-field 5k gate, share-by-link, stale-cache amber banner; all 3 smokes PASSED. Waves 16/20/21 shipped. _SCHEDULE_EXTRA_CATEGORIES critical bugfix (arch/structural warm pool); Windows smoke PASSED. Next.js 15.5.19 (CVE-2025-29927 closed). Phase 6 access tiers + billing guardrails live. Phase 4b HITL smoke PASSED.",
        "2026-06-11 - Waves 5/6/6.5 shipped: XLSX export (PR #109), thin permissions (PR #110), action-enabled HITL assistant (PR #111). Audit remediation closed: CORE-1/2/3, LIB-13, SCHED-1/2/3, ASST-1/3. 3 Dependabot bumps merged.",
        "2026-06-10 - Waves 10-17 discipline schedules close-out: 11 render modes live-smoked PASS. Wave 4.8 CLOSED. Audit B1-B6 + GA wave executed (8 PRs). S-1 + sessions.json encryption live.",
        "2026-06-09 - Perf fixes wave 4.6.5 + full-project audit (GA-C1)",
        "2026-06-07 - Schedules quick-access bar merged; assistant markdown + pill chrome",
        "2026-06-05 - ALL 7 Tier-1 electrical schedules shipped; federated viewer Wave 1; assistant help library"
      ],
      audit: {
        lastRun: "2026-06-10",
        runType: "Full top-to-bottom (7 adversarial review agents)",
        cadence: "weekly Mon 6am + on-demand",
        counts: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
        closedLastRun: 64,
        trend: "improving",
        reportPath: "F:\\AI-Dev\\BIMpossible_Workspace\\02_Reference\\Audit Reports\\2026-06-10__audit-report-full.md",
        ledgerPath: "F:\\AI-Dev\\BIMpossible_Workspace\\02_Reference\\_audit-runs.md",
        open: []
      },
      waves: {
        updated: "2026-06-12",
        source: "F:\\AI-Dev\\BIMpossible_Workspace\\00_Strategy\\BIMpossible_WAVE-STATUS.md",
        summary: { done: 19, built: 7, inFlight: 1, ahead: 5 },
        current: [
          { id: "1", title: "Foundation consolidation", status: "PARTIAL", note: "Open: Alembic baseline (HIGH-8), Phase 3.5 migration to live DB, confirm audit branches merged" },
          { id: "10-14,17", title: "Discipline schedule shapers (Arch/Mech/Plumb/Struct/FP/ICT)", status: "BUILT", date: "2026-06-10", note: "Code shipped; live smokes owed post-prod-deploy of _SCHEDULE_EXTRA_CATEGORIES fix" },
          { id: "16", title: "Interiors schedule bar config", status: "BUILT", date: "2026-06-12", note: "Bar config shipped via PR #112; no dedicated shapers yet; live smoke owed" },
          { id: "4.9", title: "Classification Enrichment (OmniClass + CSI)", status: "PLANNED", note: "Scoped 2026-06-12 in Cowork; BuildSpec + pre-written module ready; overnight-runnable; no prerequisites" },
          { id: "8", title: "Revit Link Phase 1 multi-user pass", status: "PLANNED", note: "Next code wave after prod deploy stabilizes; gates Phase 8 (Product Data Ingestion)" }
        ],
        lastCompleted: { id: "7", title: "Phase 3.9 minimal automation", date: "2026-06-12" },
        drift: [
          "No wave-*-complete git tags exist — Complete-Wave.ps1 tagging isn't in use; ledger is the sole completion signal (FYI)",
          "WAVE-STATUS.md ledger missing rows for waves 10-21 — summary counts estimated from GitHub PRs + STATE doc; add ledger rows to make counts authoritative"
        ]
      }
    },
    {
      id: "addins",
      name: "Add-Ins / RevitLink",
      icon: "wrench",
      oneLiner: "Revit ribbon add-ins: BIMpossible.RevitLink (9/13 shipped + 8 BIM manager tools built) + Trade QA Scanner suite (6 trades deployed).",
      status: "active",
      phase: "Major expansion 06-10/11: Tools 10-13 shipped (Fix Title Blocks, Retag Rooms, Push View Templates, Trim Sheets) → RevitLink 9/13 live. Tools 14-21 built via TDD (Warning Scanner, In-Place Families, Workset Audit, Element ID Finder, Batch Rename Views, VT Audit, Scope Box Manager, Batch PDF Export). ElectricalParamSyncWindow improved. feat/model-health-report retired; all pushed to main.",
      focus: "Tool 7 Phase 1 smoke test in Revit; then Definition of Done sweep (icons/guides/tooltips) for Tools 10-21",
      progress: { label: "Tracks", phases: [
        { name: "RevitLink tools (9/13 shipped)", pct: 72,
          tasks: [
            { label: "Tools 1–6 shipped", status: "done" },
            { label: "Tool 7 (Build Sheet Set from Arch Link)", status: "active", note: "Phase 1 built; smoke test owed in Revit" },
            { label: "Tools 8–9", status: "pending", note: "IDEA stage" },
            { label: "Tools 10–13 shipped", status: "done", note: "06-10: Fix Title Blocks, Retag Rooms, Push View Templates, Trim Sheets" }
          ]
        },
        { name: "BIM Manager Tools (14-21 built)", pct: 40, note: "TDD green; not yet in SHIP state; Definition of Done owed",
          tasks: [
            { label: "Tool 14 Warning Scanner", status: "done", note: "WarningScannerCommand + 6 tests" },
            { label: "Tool 15 In-Place Family Finder", status: "done", note: "TDD green" },
            { label: "Tool 16 Workset Audit", status: "done", note: "WorksetAuditEntry + 5 tests" },
            { label: "Tool 17 Element ID Finder", status: "done", note: "WPF dialog + clipboard copy" },
            { label: "Tool 18 Batch Rename Views", status: "done", note: "ViewRenameRule + 7 tests" },
            { label: "Tool 19 View Template Audit", status: "done", note: "HTML+CSV report, TDD green" },
            { label: "Tool 20 Scope Box Manager", status: "done", note: "TDD green" },
            { label: "Tool 21 Batch PDF Export", status: "done", note: "SheetExportSpec + PdfExportGrouper + 4 tests" },
            { label: "Definition of Done (icons, guides, tooltips) for 14-21", status: "pending" },
            { label: "TOOL_BACKLOG.md numbered table updated with 14-21", status: "pending" }
          ]
        },
        { name: "Tool 7 sheet set", pct: 60, note: "Phase 1 built; smoke owed",
          tasks: [
            { label: "Phase 1 (sheets) — built", status: "done" },
            { label: "Phase 1 smoke test in Revit", status: "active", note: "Next action — run it" },
            { label: "Phase 2 (view placement)", status: "pending" }
          ]
        },
        { name: "QA scanners (6/7 deployed)", pct: 72, note: "Core consolidated + audit-hardened; live smokes owed",
          tasks: [
            { label: "6 trades deployed", status: "done" },
            { label: "ModelQA.Core consolidated (816 tests green)", status: "done", note: "06-10 — 17 files × ~100 copies → one netstandard2.0 lib" },
            { label: "Audit-hardened pass", status: "done", note: "06-09 — CSV injection guard x7, culture-invariant, rolling log" },
            { label: "Architectural live smoke (4 tools, 21 tests)", status: "active" },
            { label: "E / M / P / FP / S live spikes", status: "pending" },
            { label: "Civil scanner (Trade 7)", status: "pending", note: "Scope decision parked — unanswered" }
          ]
        }
      ]},
      activity: [0,0,0,22,24,38,11,0,1,0,8,57,17,0],
      lastActivity: { date: "2026-06-11", summary: "Tools 14-21 built + ribbon-wired (8 BIM manager tools via TDD); ReportHelper shared component; deferred tool ideas documented" },
      branch: "main",
      git: { warn: "BIMpossible.RevitLink still has NO git repo (git init pending). main 0 ahead of origin/main." },
      nextActions: [
        "Tool 7 Phase 1 (sheets) smoke test; Phase 2 = view placement",
        "Definition of Done sweep: icons + How-To guides + tooltip/F1 wiring for Tools 10-21",
        "QA Scanners: live smoke Architectural (4 tools, 21 tests); live spikes for E/M/P/FP/S collectors",
        "git init BIMpossible.RevitLink",
        "Update TOOL_BACKLOG.md: add Tools 14-21 to numbered backlog table with status"
      ],
      pendingDecisions: [ "Civil Shared-Coordinate Audit scanner - scope unanswered (PARKED)" ],
      blockers: [],
      reminders: [
        "Core.dll co-loads in one Revit process: redeploy ALL add-ins together when Core changes",
        "Tools 14-21 committed to main but not yet in TOOL_BACKLOG.md numbered table — update table + assign status",
        "Definition of Done (icons, guides, tooltips) owed for all recently shipped/built tools (10-21)",
        "Deferred: Deploy-Local.ps1 PS 5.1-safe; Revit dev-mode hot-reload"
      ],
      links: [
        { label: "Tool backlog", path: "F:\\AI-Dev\\Add-Ins\\TOOL_BACKLOG.md" },
        { label: "ModelQA consolidation decision (06-10)", path: "F:\\AI-Dev\\Add-Ins\\decision-log\\2026-06-10__modelqa-consolidation.md" },
        { label: "Audit fix pass (06-09)", path: "F:\\AI-Dev\\Add-Ins\\decision-log\\2026-06-09__audit-fix-pass.md" },
        { label: "Dev notes", path: "F:\\AI-Dev\\Add-Ins\\BIMpossible.RevitLink\\DEV-NOTES.md" }
      ],
      recent: [
        "2026-06-11 - Tools 14-21 built + ribbon-wired (Warning Scanner, In-Place Families, Workset Audit, Element ID Finder, Batch Rename Views, VT Audit, Scope Box Manager, Batch PDF Export); ReportHelper shared; deferred tool ideas doc",
        "2026-06-10 - Tools 10-13 shipped (Fix Title Blocks, Retag Rooms, Push View Templates, Trim Sheets); ElectricalParamSyncWindow filter bar + auto-collapse + collapse memory; Electrical ribbon additions (Equip/One-Line sync, Link Symbols); feat/model-health-report retired",
        "2026-06-10 - ModelQA.Core consolidation: 17 files x ~100 copies -> one shared netstandard2.0 lib; 816 tests green",
        "2026-06-09 - audit fix pass: pipe B-Off enacted, culture-invariant, CSV injection guard x7, rolling log, dead-planner removal"
      ],
      audit: {
        lastRun: "2026-06-09",
        runType: "google / perp / perf (on-demand)",
        cadence: "on-demand",
        counts: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
        closedLastRun: 9,
        trend: "improving",
        reportPath: "F:\\AI-Dev\\Add-Ins\\audits\\2026-06-09__perp-audit.md",
        open: []
      }
    },
    {
      id: "site",
      name: "BIMpossible Site",
      icon: "globe",
      oneLiner: "yourbimpossible.com — LIVE at M3. Astro 4 + Cloudflare Pages + Tailwind. Lighthouse 100/100/100/100 across all 6 pages.",
      status: "active",
      phase: "M3 LIVE: yourbimpossible.com deployed on Cloudflare Pages. All 2026-06-09 audit findings cleared. LinkedIn Company Page live (linkedin.com/company/bimpossible). WAF rate rule, 5-hash CSP, Turnstile on /contact, 13.7KB font subset, 405 Allow, dead font fixed — all deployed 06-09/10. Next milestone: M4 (structured data, broken-link sweep).",
      focus: "M4 hardening — JSON-LD schema.org structured data, broken-link sweep; email routing aliases; product screenshots on interior pages",
      progress: { label: "Milestones", phases: [
        { name: "M0-M3 Foundation + live deploy", pct: 100,
          tasks: [
            { label: "Astro site scaffold (6 pages + global.css)", status: "done", note: "06-04" },
            { label: "Triple audit cleared (perf/architecture/code-review)", status: "done", note: "06-09 — all H/M/L findings fixed" },
            { label: "Cloudflare Pages deploy + custom domain yourbimpossible.com", status: "done" },
            { label: "Contact form (Turnstile + Web3Forms + 10s/15s timeouts)", status: "done", note: "13 e2e tests passing" },
            { label: "WAF rate rule + 5-hash CSP + 405 Allow header", status: "done", note: "06-09/10" },
            { label: "13.7KB font subset (dead font 404 fixed)", status: "done", note: "06-09" }
          ]
        },
        { name: "Business infra + presence", pct: 55, note: "Domain + Cloudflare live; LinkedIn live; email aliases + handles still open",
          tasks: [
            { label: "Domain registered + Cloudflare DNS live", status: "done" },
            { label: "LinkedIn Company Page live", status: "done", note: "linkedin.com/company/bimpossible (ID 131823928); launch post published" },
            { label: "Email routing aliases (hello@/support@/legal@/billing@/zeriah@)", status: "pending", note: "Recipe in IP-Lockdown-Checklist.md Phase 1.5 — not started" },
            { label: "Personal LinkedIn profile share of company page", status: "pending" },
            { label: "LLC formation", status: "pending" },
            { label: "Social handles (X, Instagram, GitHub org)", status: "pending" }
          ]
        },
        { name: "Content + product imagery", pct: 30, note: "Copy live; interior page screenshots still text-only placeholders",
          tasks: [
            { label: "6-page copy live", status: "done" },
            { label: "Leaders page — real product screenshots", status: "pending", note: "Needs live app screenshots" },
            { label: "BIM Managers page — real product screenshots", status: "pending" },
            { label: "Dashboard private sub-page (dashboard.yourbimpossible.com)", status: "pending", note: "Separate Cloudflare Pages project + Zero Trust Access gated to zeriah.t@gmail.com" }
          ]
        },
        { name: "M4 SEO hardening", pct: 0,
          tasks: [
            { label: "JSON-LD schema.org structured data (Organization, WebPage types)", status: "pending" },
            { label: "Broken-link sweep", status: "pending" },
            { label: "Open Graph / Twitter card meta per page", status: "pending" }
          ]
        },
        { name: "M5-M6 Pricing + commercial launch", pct: 0,
          tasks: [
            { label: "Pricing / waitlist page", status: "pending" },
            { label: "Commercial launch content", status: "pending" }
          ]
        }
      ]},
      activity: [1,2,1,0,0,0,1,0,0,0,2,5,3,1],
      lastActivity: { date: "2026-06-11", summary: "LinkedIn Company Page published (linkedin.com/company/bimpossible); launch post live with link preview" },
      branch: null, git: null,
      nextActions: [
        "M4: Add JSON-LD schema.org structured data (Organization + WebPage types) to all 6 pages",
        "M4: Broken-link sweep across all pages",
        "Email routing aliases: hello@/support@/legal@/billing@/zeriah@ → Gmail (recipe in IP-Lockdown-Checklist.md Phase 1.5)",
        "Product screenshots: get real app screenshots into Leaders + BIM Managers pages",
        "Dashboard sub-page: create separate Cloudflare Pages project at dashboard.yourbimpossible.com + Zero Trust Access restricted to zeriah.t@gmail.com"
      ],
      pendingDecisions: [
        "Dashboard sub-page auth: Cloudflare Zero Trust email OTP vs. service token — confirm approach before creating Pages project"
      ],
      blockers: [],
      reminders: [
        "Dashboard is still local-only — Cloudflare Pages project for dashboard.yourbimpossible.com not yet created",
        "Product screenshots needed on Leaders + BIM Managers pages before M4 can be considered complete",
        "Email aliases recipe ready in IP-Lockdown-Checklist.md — Phase 1.5 task, not yet executed"
      ],
      links: [
        { label: "Roadmap index", path: "F:\\AI-Dev\\BIMpossible Site\\00_README.md" },
        { label: "IP lockdown checklist", path: "F:\\AI-Dev\\BIMpossible Site\\IP-Lockdown-Checklist.md" },
        { label: "Build log", path: "F:\\AI-Dev\\BIMpossible Site\\01_BuildLog" },
        { label: "Site code", path: "F:\\AI-Dev\\BIMpossible Site\\site" }
      ],
      recent: [
        "2026-06-11 - LinkedIn Company Page published (linkedin.com/company/bimpossible); launch post live",
        "2026-06-10 - WAF rate rule deployed; re-verified live: 5-hash CSP, 405 Allow, Turnstile on /contact, dead font 404 fixed, 13.7KB font subset",
        "2026-06-09/10 - All audit findings cleared + deployed; Lighthouse 100/100/100/100 across all 6 pages",
        "2026-06-09 - Triple audit (perf/architecture/code-review); contact form Turnstile + Web3Forms live; 13 e2e tests"
      ],
      audit: {
        lastRun: "2026-06-10",
        runType: "Full triple audit (perf + architecture + code-review) + re-verify 06-10",
        cadence: "on-demand",
        counts: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
        closedLastRun: 30,
        trend: "stable",
        reportPath: "F:\\AI-Dev\\BIMpossible Site\\01_BuildLog\\_site-audit-runs.md",
        open: []
      }
    },
    {
      id: "pickem",
      name: "Preseason Pick'em",
      icon: "trophy",
      oneLiner: "Next.js pick'em app (PreseasonPickem-app). Stack locked, Phase 1 auth started.",
      status: "dormant",
      phase: "Phase 1 auth + scoring/rankings libs added 06-01 (status still flagged dormant pending human call)",
      focus: "Decide: resume before NFL preseason or park explicitly",
      progress: { label: "Build", phases: [
        { name: "P0 Bootstrap + stack", pct: 100,
          tasks: [
            { label: "Next.js + stack setup", status: "done" },
            { label: "Docker compose + scripts", status: "done" }
          ]
        },
        { name: "P1 Auth", pct: 25,
          tasks: [
            { label: "Auth lib scaffolded", status: "done" },
            { label: "User sessions + flows", status: "active", note: "Ref: 03_ChatExports/2026-05-24__phase1-auth.md" }
          ]
        },
        { name: "Picks + scoring MVP", pct: 30, note: "scoring engine/leaderboard + rankings sync libs in (06-01)",
          tasks: [
            { label: "Scoring engine lib", status: "done", note: "06-01" },
            { label: "Leaderboard lib", status: "done", note: "06-01" },
            { label: "Rankings sync (Sleeper / stats)", status: "done", note: "06-01" },
            { label: "Wire libs into app", status: "pending" },
            { label: "Pick submission UI", status: "pending" }
          ]
        },
        { name: "Deploy", pct: 0,
          tasks: [
            { label: "Hosting setup", status: "pending" },
            { label: "Production deploy", status: "pending", note: "Hard deadline: NFL preseason (August)" }
          ]
        }
      ]},
      activity: [0,0,1,0,0,0,0,0,0,0,0,0,0,0],
      lastActivity: { date: "2026-06-01", summary: "rankings (sleeper/stats/sync) + scoring (engine/leaderboard/manual-tiebreak) libs added" },
      branch: null, git: null,
      nextActions: [ "Resume Phase 1 auth per 03_ChatExports/2026-05-24__phase1-auth.md; wire the new scoring/rankings libs into the app" ],
      pendingDecisions: [],
      blockers: [],
      reminders: [
        "Idle since 2026-06-01 (11 days) - confirm dormant status; NFL preseason deadline approaching (August)",
        "Hard real-world deadline: NFL preseason (August)"
      ],
      links: [
        { label: "PRD", path: "F:\\AI-Dev\\Preseason Pick'em\\PRD.md" },
        { label: "Workspace index", path: "F:\\AI-Dev\\Preseason Pick'em\\WORKSPACE_INDEX.md" },
        { label: "App", path: "F:\\AI-Dev\\Preseason Pick'em\\PreseasonPickem-app" }
      ],
      recent: [
        "2026-06-01 - rankings + scoring engine/leaderboard libs added"
      ]
    },
    {
      id: "laundry",
      name: "Laundry Gig",
      icon: "box",
      oneLiner: "Next.js demo app (Lazy Demo) with docker-compose + start/stop scripts.",
      status: "dormant",
      phase: "Unknown - no state doc exists",
      focus: "Capture a status note so this becomes trackable",
      progress: null,
      activity: [0,0,1,0,1,0,0,0,0,0,0,0,0,0],
      lastActivity: { date: "2026-06-04", summary: "CLAUDE-CODE-PROMPT.md added (06-04); app scaffold (package/prisma/scripts) touched 06-01" },
      branch: null, git: null,
      nextActions: [ "Write a status note - dashboard can't track this project until one exists" ],
      pendingDecisions: [],
      blockers: [],
      reminders: ["No state doc - tracking is folder-mtime only"],
      links: [
        { label: "README", path: "F:\\AI-Dev\\Laundry Gig\\README.md" },
        { label: "Docs", path: "F:\\AI-Dev\\Laundry Gig\\docs" }
      ],
      recent: []
    },
    {
      id: "families",
      name: "Families by AI",
      icon: "cube",
      oneLiner: "Revit family audit + standardize tool (Family Fixer). Path A: offline Python auditor. Path B: C# revit-mcp automation. Focus: S&L One-Line electrical symbol families.",
      status: "paused",
      phase: "Git repo scaffolded 06-11 (code-only, no .rfa binaries). Path A (Python auditor) + Path B (C# Revit scripts via revit-mcp). Developmental/One Line Symbols folder updated 06-11 (ties into Add-Ins One-Line sync work).",
      focus: "Run Path A auditor against a real .rfa repo; green-light Path B only after it validates",
      progress: { label: "Two-path plan", phases: [
        { name: "Path A auditor build", pct: 60,
          tasks: [
            { label: "Tool scaffold + README", status: "done", note: "05-28" },
            { label: "Core auditor logic (partial)", status: "active", note: "~60% built; untouched 05-28 to 06-11" }
          ]
        },
        { name: "Path A validation", pct: 0,
          tasks: [
            { label: "Run against a real .rfa repo", status: "pending", note: "Must pass before Path B starts" }
          ]
        },
        { name: "Path B live automation", pct: 0,
          tasks: [
            { label: "revit-mcp integration design", status: "pending", note: "Not started - blocked on Path A validation" },
            { label: "Live automation build", status: "pending" }
          ]
        }
      ]},
      activity: [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
      lastActivity: { date: "2026-06-11", summary: "Git repo scaffolded (.gitignore code-only/no-.rfa, .gitattributes, LICENSE, CHANGELOG); Developmental/One Line Symbols folder updated (linked to Add-Ins electrical sync work)" },
      branch: null, git: null,
      nextActions: [ "Run Path A against a real family repo; green-light Path B only after it validates" ],
      pendingDecisions: [],
      blockers: [],
      reminders: [
        "New activity 06-11 (git scaffolding + One Line Symbols) but status remains paused per auto-promote rule",
        "Idle 05-28 to 06-11 on core auditor; auto-demote to dormant at 21 idle days on core auditor (rule 7)"
      ],
      links: [ { label: "Tool README", path: "F:\\AI-Dev\\Families by AI\\README.md" } ],
      recent: [
        "2026-06-11 - git repo scaffolded (code-only, no .rfa binaries); Developmental/One Line Symbols folder updated"
      ]
    }
  ]
};
