// Auto-generated by usage_sync.mjs — Claude Code usage via ccusage.
// Cost = API-equivalent value (subscription, not cash paid). Do not hand-edit.
window.DASHBOARD_USAGE = {
  "generated": "2026-10-07T13:00:25.743Z",
  "source": "ccusage (local ~/.claude usage, API-equivalent pricing)",
  "allTime": {
    "cost": 22906.86,
    "totalTokens": 24195283051,
    "inputTokens": 9707213,
    "outputTokens": 144694522,
    "cacheCreationTokens": 1075085098,
    "cacheReadTokens": 22965796218,
    "days": 85,
    "firstDay": "2026-06-16",
    "lastDay": "2026-10-07"
  },
  "today": {
    "date": "2026-10-07",
    "cost": 2.82,
    "tokens": 7211414
  },
  "thisMonth": {
    "month": "2026-10",
    "cost": 1462.53,
    "tokens": 2174996967
  },
  "last14": [
    {
      "date": "2026-09-20",
      "cost": 63.89,
      "tokens": 74014284
    },
    {
      "date": "2026-09-21",
      "cost": 395.2,
      "tokens": 460235176
    },
    {
      "date": "2026-09-22",
      "cost": 247.01,
      "tokens": 278613758
    },
    {
      "date": "2026-09-23",
      "cost": 475.68,
      "tokens": 531568471
    },
    {
      "date": "2026-09-24",
      "cost": 606.09,
      "tokens": 944729528
    },
    {
      "date": "2026-09-25",
      "cost": 347.56,
      "tokens": 562939701
    },
    {
      "date": "2026-09-26",
      "cost": 412.12,
      "tokens": 579135903
    },
    {
      "date": "2026-09-28",
      "cost": 18.45,
      "tokens": 32959043
    },
    {
      "date": "2026-09-29",
      "cost": 274.66,
      "tokens": 329232744
    },
    {
      "date": "2026-09-30",
      "cost": 53.04,
      "tokens": 112493667
    },
    {
      "date": "2026-10-01",
      "cost": 82.57,
      "tokens": 134163364
    },
    {
      "date": "2026-10-05",
      "cost": 676.33,
      "tokens": 987897658
    },
    {
      "date": "2026-10-06",
      "cost": 700.8,
      "tokens": 1045724531
    },
    {
      "date": "2026-10-07",
      "cost": 2.82,
      "tokens": 7211414
    }
  ],
  "byModel": [
    {
      "model": "claude-opus-4-8",
      "cost": 6204.63,
      "tokens": 5629408267
    },
    {
      "model": "claude-fable-5",
      "cost": 5579.67,
      "tokens": 2720447888
    },
    {
      "model": "claude-opus-5",
      "cost": 3474.15,
      "tokens": 3644179319
    },
    {
      "model": "claude-fable-5-1",
      "cost": 2762.96,
      "tokens": 1980349311
    },
    {
      "model": "claude-sonnet-5",
      "cost": 2481.97,
      "tokens": 5862782305
    },
    {
      "model": "claude-opus-5-5",
      "cost": 2264.26,
      "tokens": 4052211308
    },
    {
      "model": "claude-sonnet-5-5",
      "cost": 85.71,
      "tokens": 229095341
    },
    {
      "model": "claude-sonnet-4-6",
      "cost": 49.67,
      "tokens": 65086293
    },
    {
      "model": "claude-haiku-4-5",
      "cost": 3.27,
      "tokens": 9229521
    },
    {
      "model": "qwen3-coder-32k",
      "cost": 0.54,
      "tokens": 2403655
    },
    {
      "model": "qwen3-coder:30b-a3b-q4_K_M",
      "cost": 0.02,
      "tokens": 71214
    },
    {
      "model": "qwen2.5-coder:14b",
      "cost": 0,
      "tokens": 18629
    }
  ]
};
