// Auto-generated by usage_sync.mjs — Claude Code usage via ccusage.
// Cost = API-equivalent value (subscription, not cash paid). Do not hand-edit.
window.DASHBOARD_USAGE = {
  "generated": "2026-06-28T18:54:35.013Z",
  "source": "ccusage (local ~/.claude usage, API-equivalent pricing)",
  "allTime": {
    "cost": 15334.29,
    "totalTokens": 14237648581,
    "inputTokens": 14697907,
    "outputTokens": 89036685,
    "cacheCreationTokens": 657173540,
    "cacheReadTokens": 13476740449,
    "days": 38,
    "firstDay": "2026-05-10",
    "lastDay": "2026-06-28"
  },
  "today": {
    "date": "2026-06-28",
    "cost": 215.67,
    "tokens": 201932161
  },
  "thisMonth": {
    "month": "2026-06",
    "cost": 12361.93,
    "tokens": 11150120452
  },
  "last14": [
    {
      "date": "2026-06-12",
      "cost": 663.06,
      "tokens": 645352185
    },
    {
      "date": "2026-06-13",
      "cost": 631.75,
      "tokens": 637602980
    },
    {
      "date": "2026-06-14",
      "cost": 541.38,
      "tokens": 481412377
    },
    {
      "date": "2026-06-15",
      "cost": 31.92,
      "tokens": 23933264
    },
    {
      "date": "2026-06-16",
      "cost": 351.18,
      "tokens": 352018323
    },
    {
      "date": "2026-06-17",
      "cost": 394.2,
      "tokens": 285448801
    },
    {
      "date": "2026-06-18",
      "cost": 154.19,
      "tokens": 109083012
    },
    {
      "date": "2026-06-21",
      "cost": 1.14,
      "tokens": 441961
    },
    {
      "date": "2026-06-23",
      "cost": 448.31,
      "tokens": 299416680
    },
    {
      "date": "2026-06-24",
      "cost": 167.99,
      "tokens": 115899870
    },
    {
      "date": "2026-06-25",
      "cost": 434.9,
      "tokens": 375006423
    },
    {
      "date": "2026-06-26",
      "cost": 282.07,
      "tokens": 226929677
    },
    {
      "date": "2026-06-27",
      "cost": 464.38,
      "tokens": 475631007
    },
    {
      "date": "2026-06-28",
      "cost": 215.67,
      "tokens": 201932161
    }
  ],
  "byModel": [
    {
      "model": "claude-opus-4-8",
      "cost": 12187.55,
      "tokens": 10943834546
    },
    {
      "model": "claude-fable-5",
      "cost": 1328.39,
      "tokens": 767530858
    },
    {
      "model": "claude-opus-4-7",
      "cost": 901.62,
      "tokens": 990100198
    },
    {
      "model": "claude-sonnet-4-6",
      "cost": 871.75,
      "tokens": 1386092266
    },
    {
      "model": "claude-haiku-4-5",
      "cost": 29.62,
      "tokens": 134042978
    },
    {
      "model": "claude-opus-4-6",
      "cost": 15.35,
      "tokens": 16047735
    }
  ]
};
