#!/usr/bin/env node
/**
 * Claude Code usage -> dashboard sync.
 *
 * Runs `ccusage` (reads LOCAL ~/.claude usage data, no API key), builds a compact
 * window.DASHBOARD_USAGE object, writes it to usage.js in the dashboard repo, and
 * pushes. Because ccusage reads local files, this MUST run on the user's machine
 * (Windows Task Scheduler / on-demand) — it can't run in GitHub Actions.
 *
 * Cost = API list-price equivalent. The user is on a Claude subscription, so this
 * is the value of usage at pay-as-you-go rates, NOT money actually paid.
 *
 * Usage:  node usage_sync.mjs            (sync + git push)
 *         node usage_sync.mjs --no-push  (just regenerate usage.js locally)
 */
import { execSync } from "node:child_process";
import { writeFileSync, readFileSync, existsSync } from "node:fs";

const REPO = "F:/AI-Dev/Dashboard";
const OUT = `${REPO}/usage.js`;
const PUSH = !process.argv.includes("--no-push");

function ccusage(cmd) {
  const raw = execSync(`npx -y ccusage@latest ${cmd} --json`, {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
    stdio: ["ignore", "pipe", "ignore"],
  });
  return JSON.parse(raw);
}

function ymd(d) {
  return d.toISOString().slice(0, 10);
}

console.log("Running ccusage…");
const { daily, totals } = ccusage("daily");
if (!Array.isArray(daily) || !daily.length) {
  console.error("No daily usage returned — aborting.");
  process.exit(1);
}

const today = ymd(new Date());
const thisMonth = today.slice(0, 7); // YYYY-MM

// Per-model aggregation across all days
const modelAgg = {};
for (const day of daily) {
  for (const mb of day.modelBreakdowns || []) {
    const m = (modelAgg[mb.modelName] ||= { cost: 0, tokens: 0 });
    m.cost += mb.cost || 0;
    m.tokens +=
      (mb.inputTokens || 0) +
      (mb.outputTokens || 0) +
      (mb.cacheCreationTokens || 0) +
      (mb.cacheReadTokens || 0);
  }
}
const byModel = Object.entries(modelAgg)
  .map(([model, v]) => ({ model: model.replace(/-\d{8}$/, ""), cost: +v.cost.toFixed(2), tokens: v.tokens }))
  .sort((a, b) => b.cost - a.cost);

const monthDays = daily.filter((d) => (d.period || "").startsWith(thisMonth));
const monthCost = monthDays.reduce((s, d) => s + (d.totalCost || 0), 0);
const monthTok = monthDays.reduce((s, d) => s + (d.totalTokens || 0), 0);

const todayRow = daily.find((d) => d.period === today) || null;

const last14 = daily.slice(-14).map((d) => ({
  date: d.period,
  cost: +(d.totalCost || 0).toFixed(2),
  tokens: d.totalTokens || 0,
}));

const usage = {
  generated: new Date().toISOString(),
  source: "ccusage (local ~/.claude usage, API-equivalent pricing)",
  allTime: {
    cost: +totals.totalCost.toFixed(2),
    totalTokens: totals.totalTokens,
    inputTokens: totals.inputTokens,
    outputTokens: totals.outputTokens,
    cacheCreationTokens: totals.cacheCreationTokens,
    cacheReadTokens: totals.cacheReadTokens,
    days: daily.length,
    firstDay: daily[0].period,
    lastDay: daily[daily.length - 1].period,
  },
  today: todayRow
    ? { date: today, cost: +(todayRow.totalCost || 0).toFixed(2), tokens: todayRow.totalTokens || 0 }
    : { date: today, cost: 0, tokens: 0 },
  thisMonth: { month: thisMonth, cost: +monthCost.toFixed(2), tokens: monthTok },
  last14,
  byModel,
};

// Skip entirely if nothing but the timestamp changed (avoids noisy commits).
const stripGen = (u) => { const c = { ...u }; delete c.generated; return JSON.stringify(c); };
if (existsSync(OUT)) {
  try {
    const m = readFileSync(OUT, "utf8").match(/window\.DASHBOARD_USAGE\s*=\s*([\s\S]*?);\s*$/);
    if (m && stripGen(JSON.parse(m[1])) === stripGen(usage)) {
      console.log("No usage change since last run — skipping write/push.");
      process.exit(0);
    }
  } catch { /* fall through and rewrite */ }
}

const banner =
  "// Auto-generated by usage_sync.mjs — Claude Code usage via ccusage.\n" +
  "// Cost = API-equivalent value (subscription, not cash paid). Do not hand-edit.\n";
writeFileSync(OUT, banner + "window.DASHBOARD_USAGE = " + JSON.stringify(usage, null, 2) + ";\n", "utf8");
console.log(
  `usage.js written: $${usage.allTime.cost} all-time, $${usage.today.cost} today, ${usage.byModel.length} models.`
);

if (!PUSH) {
  console.log("--no-push set, skipping git.");
  process.exit(0);
}

function git(args) {
  return execSync(`git -C "${REPO}" ${args}`, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
}
try {
  git("pull --rebase --autostash origin main");
  git("add usage.js");
  const status = git("status --porcelain usage.js").trim();
  if (!status) {
    console.log("usage.js unchanged — nothing to push.");
    process.exit(0);
  }
  git(`commit -m "usage: refresh Claude Code spend (${today})" -- usage.js`);
  git("push origin main");
  console.log("Pushed usage.js to dashboard.");
} catch (e) {
  console.error("git step failed:", e.message);
  process.exit(1);
}
