// Auto-generated by usage_sync.mjs — Claude Code usage via ccusage.
// Cost = API-equivalent value (subscription, not cash paid). Do not hand-edit.
window.DASHBOARD_USAGE = {
  "generated": "2026-06-13T05:46:52.609Z",
  "source": "ccusage (local ~/.claude usage, API-equivalent pricing)",
  "allTime": {
    "cost": 12615.23,
    "totalTokens": 12735383525,
    "inputTokens": 5715721,
    "outputTokens": 66711625,
    "cacheCreationTokens": 491666918,
    "cacheReadTokens": 12171289261,
    "days": 28,
    "firstDay": "2026-05-11",
    "lastDay": "2026-06-13"
  },
  "today": {
    "date": "2026-06-13",
    "cost": 186.34,
    "tokens": 161399085
  },
  "thisMonth": {
    "month": "2026-06",
    "cost": 8197.14,
    "tokens": 7516547427
  },
  "last14": [
    {
      "date": "2026-05-31",
      "cost": 907.33,
      "tokens": 920461237
    },
    {
      "date": "2026-06-01",
      "cost": 596.4,
      "tokens": 711161474
    },
    {
      "date": "2026-06-02",
      "cost": 417.86,
      "tokens": 380832922
    },
    {
      "date": "2026-06-03",
      "cost": 684.78,
      "tokens": 652126959
    },
    {
      "date": "2026-06-04",
      "cost": 995.8,
      "tokens": 952958269
    },
    {
      "date": "2026-06-05",
      "cost": 1076.58,
      "tokens": 921022052
    },
    {
      "date": "2026-06-06",
      "cost": 437.36,
      "tokens": 348541662
    },
    {
      "date": "2026-06-07",
      "cost": 488.81,
      "tokens": 285514590
    },
    {
      "date": "2026-06-08",
      "cost": 34.42,
      "tokens": 26354959
    },
    {
      "date": "2026-06-09",
      "cost": 327.81,
      "tokens": 244792328
    },
    {
      "date": "2026-06-10",
      "cost": 1936.89,
      "tokens": 1515450309
    },
    {
      "date": "2026-06-11",
      "cost": 439.01,
      "tokens": 582447162
    },
    {
      "date": "2026-06-12",
      "cost": 575.07,
      "tokens": 733945656
    },
    {
      "date": "2026-06-13",
      "cost": 186.34,
      "tokens": 161399085
    }
  ],
  "byModel": [
    {
      "model": "claude-opus-4-8",
      "cost": 8236.49,
      "tokens": 7651354318
    },
    {
      "model": "claude-opus-4-7",
      "cost": 2189.32,
      "tokens": 2813604127
    },
    {
      "model": "claude-fable-5",
      "cost": 1328.39,
      "tokens": 767530858
    },
    {
      "model": "claude-sonnet-4-6",
      "cost": 781.82,
      "tokens": 1310569260
    },
    {
      "model": "claude-opus-4-6",
      "cost": 48.77,
      "tokens": 54065929
    },
    {
      "model": "claude-haiku-4-5",
      "cost": 30.44,
      "tokens": 138259033
    }
  ]
};
