"""Write the browser-facing artefacts.

Two files, deliberately split by who pays for them:

* ``bimwatch.js``  -- the briefing plus a recent window of items, published as
  ``window.DASHBOARD_BIMWATCH`` to match the dashboard's existing convention
  (``claude_api.js``, ``github_actions.js``). Loaded on every page view, so it stays
  small and bounded.

* ``bimwatch-archive.json`` -- the full archive. Fetched only when someone searches
  past the recent window, and read server-side by the chat Function. At the 5000-item
  retention cap this is on the order of a megabyte; putting it in the always-loaded
  bundle would tax every page view to serve a rare query.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone

# How many recent items ship in the always-loaded file. Comfortably more than a
# month of traffic at observed volumes (~300 items/run across 12 sources), so ordinary
# browsing and search never trigger the archive fetch.
RECENT_WINDOW = 300

BANNER = """// bimwatch.js -- GENERATED by bimwatch/run.py. Do not edit by hand.
//
// Regenerate:  python -m bimwatch.run --once
// Sources:     bimwatch/sources.json      (edit freely -- data, not code)
// Relevance:   bimwatch/profile.md        (edit this to retune the briefing)
//
// Written {generated} from {count} archived items.
"""


def slim_for_browser(item: dict) -> dict:
    """Drop everything the panel does not render. Halves the payload."""
    classification = item.get("classification") or {}
    return {
        "id": item.get("id"),
        "t": item.get("title"),
        "u": item.get("url"),
        "s": item.get("source"),
        "d": item.get("published"),
        "x": (item.get("summary") or "")[:280],
        "tier": classification.get("tier") or "unsorted",
        "rel": classification.get("relevance", 0),
        "why": classification.get("why", ""),
        "tags": classification.get("topics", []),
    }


def render_js(archive: list[dict], briefing: dict, sources: list[dict],
              health: dict, stale: list[dict], *, now: datetime | None = None) -> str:
    now = now or datetime.now(timezone.utc)
    payload = {
        "generated_at": now.isoformat().replace("+00:00", "Z"),
        "briefing": briefing,
        "recent": [slim_for_browser(i) for i in archive[:RECENT_WINDOW]],
        "archive_count": len(archive),
        "archive_url": "bimwatch-archive.json",
        "sources": [
            {
                "key": s["key"],
                "name": s.get("name", s["key"]),
                "home": s.get("home", ""),
                "category": s.get("category", ""),
                "stale": bool(health.get(s["key"], {}).get("stale")),
                "last_success": health.get(s["key"], {}).get("last_success"),
                "last_error": health.get(s["key"], {}).get("last_error"),
            }
            for s in sources
        ],
        "stale_sources": stale,
    }
    # Compact: this file is generated, machine-read, and shipped on every page view.
    # Indentation cost ~20 KB per render for zero human benefit.
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    banner = BANNER.format(generated=payload["generated_at"], count=len(archive))
    return f"{banner}window.DASHBOARD_BIMWATCH = {body};\n"


def write_all(out_dir: str, archive: list[dict], briefing: dict, sources: list[dict],
              health: dict, stale: list[dict], *, now: datetime | None = None) -> dict:
    """Write both artefacts. Returns the paths and their sizes, for the run log."""
    now = now or datetime.now(timezone.utc)
    os.makedirs(out_dir, exist_ok=True)

    js_path = os.path.join(out_dir, "bimwatch.js")
    with open(js_path, "w", encoding="utf-8") as handle:
        handle.write(render_js(archive, briefing, sources, health, stale, now=now))

    archive_path = os.path.join(out_dir, "bimwatch-archive.json")
    with open(archive_path, "w", encoding="utf-8") as handle:
        json.dump(
            {
                "generated_at": now.isoformat().replace("+00:00", "Z"),
                "count": len(archive),
                "items": [slim_for_browser(i) for i in archive],
            },
            handle, ensure_ascii=False, separators=(",", ":"),
        )

    return {
        "bimwatch.js": os.path.getsize(js_path),
        "bimwatch-archive.json": os.path.getsize(archive_path),
    }
